### ISSUE TITLE
TileEntityFurnace cannot be cast to TileEntityLootable

### ISSUE THREAD

**Issue by Naghtrion** [FabioZumbi12/RedProtect#116]
Oi, estou usando o spigot 1.11 e esta dando este erro quando o player abre a fornalha:

[Server thread/ERROR]: Could not pass event PlayerInteractEvent to RedProtect v7.0.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:110) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:821) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: net.minecraft.server.v1_11_R1.TileEntityFurnace cannot be cast to net.minecraft.server.v1_11_R1.TileEntityLootable
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftLootable.<init>(CraftLootable.java:17) ~[minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftFurnace.<init>(CraftFurnace.java:15) ~[minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftBlock.getState(CraftBlock.java:276) ~[minecraft_server.jar:git-Spigot-16c940b-0805f60]
	at br.net.fabiozumbi12.RedProtect.listeners.RPPlayerListener.onPlayerInteract(RPPlayerListener.java:248) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-16c940b-0805f60]
	... 18 more

**Comment by FabioZumbi12** [comment]
Parece que vc ta usando uma versão mais antiga. Esse erro não existe mais.
