### ISSUE TITLE
UUID COVERTING PROBLEMS

### ISSUE THREAD

**Issue by iamadcat** [FabioZumbi12/RedProtect#118]
when i turned to offline-mode, there are so many error messages every tries for converting uuid to nickname. so i wanted to know why this happened, i visited every profiles like 'https://api.mojang.com/user/profiles/1a953c948d4141f18d96195ecb7893c7/names', it displays  '{"error":"TooManyRequestsException","errorMessage":"The client has sent too many requests within a certain amount of time"}'.

```
[03:18:31 WARN]: java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/user/profiles/1a953c948d4141f18d96195ecb7893c7/names
[03:18:31 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[03:18:31 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[03:18:31 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[03:18:31 WARN]:        at java.net.URL.openStream(Unknown Source)
[03:18:31 WARN]:        at br.net.fabiozumbi12.RedProtect.hooks.MojangUUIDs.getName(MojangUUIDs.java:40)
[03:18:31 WARN]:        at br.net.fabiozumbi12.RedProtect.RPUtil.ReadAllDB(RPUtil.java:473)
[03:18:31 WARN]:        at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:199)
[03:18:31 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[03:18:31 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[03:18:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:18:31 WARN]:        at br.net.fabiozumbi12.RedProtect.listeners.RPCommands.onCommand(RPCommands.java:929)
[03:18:31 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[03:18:31 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[03:18:31 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)
[03:18:31 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1337)
[03:18:31 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1172)
[03:18:31 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[03:18:31 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[03:18:31 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[03:18:31 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[03:18:31 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[03:18:31 WARN]:        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[03:18:31 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[03:18:31 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[03:18:31 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[03:18:31 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[03:18:31 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by FabioZumbi12** [comment]
Seems the mojang server is overloaded, or your servers sends too many connections to mojang.

When this happens, you only need to run the server again to continue the convertion. Will continue from where stoped.
