### ISSUE TITLE
Bug in 6.3.6

### ISSUE THREAD

**Issue by Aslaak** [FabioZumbi12/RedProtect#12]
hello,

I have RedProtect 6.3.6 on my server and there is a bug who spam the console permanently, and it cause lag I think ( log.txt 200-300mo often ), this is the bug : 

[Server thread/ERROR]: Could not pass event SecondaryAbilityWeightedActivationCheckEvent to RedProtect v6.3.6
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at com.gmail.nossr50.util.skills.SkillUtils.activationSuccessful(SkillUtils.java:203) [mcMMO(1).jar:?]
	at com.gmail.nossr50.util.skills.SkillUtils.activationSuccessful(SkillUtils.java:197) [mcMMO(1).jar:?]
	at com.gmail.nossr50.skills.acrobatics.AcrobaticsManager.rollCheck(AcrobaticsManager.java:89) [mcMMO(1).jar:?]
	at com.gmail.nossr50.listeners.EntityListener.onEntityDamage(EntityListener.java:270) [mcMMO(1).jar:?]
	at sun.reflect.GeneratedMethodAccessor268.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:86) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:552) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:538) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:584) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1101) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:742) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityLiving.e(EntityLiving.java:938) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityHuman.e(EntityHuman.java:1440) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.Block.a(Block.java:640) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.Entity.a(Entity.java:810) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityLiving.a(EntityLiving.java:160) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityPlayer.a(EntityPlayer.java:621) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:456) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at br.net.fabiozumbi12.RedProtect.Region.getFlagBool(Region.java:578) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Region.canPVP(Region.java:910) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.hooks.McMMoListener.onPlayerActivateSecAbillity(McMMoListener.java:89) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor296.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	... 41 more

**Comment by FabioZumbi12** [comment]
Whats is the version of the plugin mcmmo are you using?

**Comment by Aslaak** [comment]
I use 1.5.00-b3547

**Comment by FabioZumbi12** [comment]
You removed the flag PvP from your server or from /rp flag GUI?? The error is the plugin didn't found the flag PVP.

**Comment by Aslaak** [comment]
the pvp is off in the server.properties and off or disallow with all plugin who can do that ( multiverse, worldguard )

**Comment by FabioZumbi12** [comment]
I mean on RedProtect, you disabled the flag pvp con config.yml?

**Comment by Aslaak** [comment]
yes

**Comment by Aslaak** [comment]
( false ) on line 107

**Comment by FabioZumbi12** [comment]
The correct configuration is you remove only the flag from this list:

flags-configuration:
  enabled-flags:
  - pvp
  - chest
  - lever
  - button
  - door
  - smart-door
  - spawn-monsters
  - spawn-animals
  - passives
  - flow
  - fire
  - minecart
  - allow-potions
  - allow-home
  - allow-magiccarpet
  - mob-loot

And DONT remove from here:

flags:
  pvp: false
  chest: false
  lever: false
  button: false
  door: false
  allow-potions: true
  smart-door: true
  spawn-monsters: true
  spawn-animals: true
  passives: false
  flow: true
  fire: false
  minecart: false
  allow-home: false
  allow-magiccarpet: true
  mob-loot: false

In this list you need to set to false but not remove!

**Comment by Aslaak** [comment]
this is my config ...

http://pastebin.com/9KR1S14M

**Comment by FabioZumbi12** [comment]
I think found the problem, will be fixed on next version!

**Comment by Aslaak** [comment]
thanks you :D !

**Comment by Aslaak** [comment]
when the next version will be released ? :)

**Comment by Aslaak** [comment]
fixed in the new version ?

**Comment by FabioZumbi12** [comment]
I think yes, download and test, please.

**Comment by Aslaak** [comment]
i have a new bug, i posted it in issues

**Comment by FabioZumbi12** [comment]
OK, and this error was fixed right?

**Comment by Aslaak** [comment]
yes :D
