### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PeRFecTxTabZ** [FabioZumbi12/RedProtect#124]
[19:59:58 INFO]: Redprotect: [All configurations loaded!]
[19:59:58 WARN]: java.lang.NullPointerException
[19:59:58 WARN]:        at br.net.fabiozumbi12.RedProtect.config.RPLang.init(RPLang.java:52)
[19:59:58 WARN]:        at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:122)
[19:59:58 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[19:59:58 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[19:59:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:59:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[19:59:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[19:59:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741)
[19:59:58 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:535)
[19:59:58 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[19:59:58 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[19:59:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[19:59:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[19:59:58 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[19:59:58 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[19:59:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[19:59:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[19:59:58 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:59:58 INFO]: Redprotect: [Error enabling RedProtect, plugin will shut down.]
[19:59:58 INFO]: Redprotect: [RedProtect v7.1.1 disabled.]

hey, i have this startup error. Can u help me i dont know how to fix it.

**Comment by FabioZumbi12** [comment]
Try this version: https://discord.gg/RyEVJC3

**Comment by PeRFecTxTabZ** [comment]
Discord? Sry what is that.

**Comment by PeRFecTxTabZ** [comment]
ok, i will try it thanks
