### ISSUE TITLE
On Shuttdown of the server (restart too) i get this info when Redprtoect disables)

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#127]
[10:51:19] [Server thread/ERROR]: Error occurred while disabling RedProtect v7.1.1 (Is it up to date?)
java.lang.NullPointerException
	at br.net.fabiozumbi12.RedProtect.RegionManager.unloadAll(RegionManager.java:53) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RedProtect.onDisable(RedProtect.java:94) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345) [spigot.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:462) [spigot.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:610) [spigot.jar:git-Spigot-0b1090d-7fdc749]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by FabioZumbi12** [comment]
I found the problem. Wil be fixed on next version (or on discord) ;)
