### ISSUE TITLE
Can't /rp claim in 1.11.2

### ISSUE THREAD

**Issue by LemonLight** [FabioZumbi12/RedProtect#138]
Hi there :)

I recently update in 1.11.2 (git-Spigot-b4417b8-3c48711) and now when I run /rp claim I get this
Version of RedProtect : 7.1.1
```
[22:03:21] [Server thread/WARN]: java.sql.SQLException: Incorrect integer value: 'true' for column 'candelete' at row 1
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
[22:03:21] [Server thread/WARN]:     at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
[22:03:21] [Server thread/WARN]:     at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.addLiveRegion(WorldMySQLRegionManager.java:173)
[22:03:21] [Server thread/WARN]:     at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.add(WorldMySQLRegionManager.java:144)
[22:03:21] [Server thread/WARN]:     at br.net.fabiozumbi12.RedProtect.RegionManager.add(RegionManager.java:178)
[22:03:21] [Server thread/WARN]:     at br.net.fabiozumbi12.RedProtect.listeners.RPCommands.onCommand(RPCommands.java:1022)
[22:03:21] [Server thread/WARN]:     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:03:21] [Server thread/WARN]:     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:03:21] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:03:21] [Server thread/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:03:21] [Server thread/WARN]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[22:03:21] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:745)
[22:03:21] [Server thread/WARN]: java.lang.NullPointerException
[22:03:21] [Server thread/WARN]:     at br.net.fabiozumbi12.RedProtect.RegionManager.add(RegionManager.java:181)
[22:03:21] [Server thread/WARN]:     at br.net.fabiozumbi12.RedProtect.listeners.RPCommands.onCommand(RPCommands.java:1022)
[22:03:21] [Server thread/WARN]:     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:03:21] [Server thread/WARN]:     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:03:21] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:03:21] [Server thread/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:03:21] [Server thread/WARN]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[22:03:21] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[22:03:21] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:745)
```

Thanks for your help :)

**Comment by FabioZumbi12** [comment]
Try this version (on discord): https://discord.gg/RyEVJC3

**Comment by LemonLight** [comment]
Yes it looks good now :) It works again :D 
I still have errors in console, maybe due to a missing dynmap's module ? (I have got dynmap-2.4, dynmap-WorldGuard and dynmap-Essentials)
```
[20:49:21] [Server thread/INFO]: LemonLight29 issued server command: /rp claim
[20:49:24] [Server thread/WARN]: java.lang.NullPointerException
[20:49:24] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RegionManager.add(RegionManager.java:181)
[20:49:24] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.listeners.RPCommands.onCommand(RPCommands.java:1025)
[20:49:24] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:49:24] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[20:49:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[20:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[20:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[20:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:49:24] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:49:24] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[20:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[20:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[20:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[20:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[20:49:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:49:24] [Server thread/INFO]: Redprotect: [Problems when add marks to Dynmap. Dynmap is updated?]
```

**Comment by CloudeLecaw** [comment]
[20:49:24] [Server r thread/INFO]: Redprotect: [Problems when add marks to Dynmap. Dynmap is updated?]...
Im no dev..but is Dynmap up to date and configutated correct?
or maybe redProtect does not work correct with latest version of Dynmap (if hook is enabled)
just a suggestion what it could be...

**Comment by LemonLight** [comment]
Yes I am using the last version of Redprotect et Dynmap.
It only was to tell to FabioZumbi12 the region does not appear on dynmap. Maybe he will fix that later. :)
