### ISSUE TITLE
ERROR: Could not pass event PrepareItemCraftEvent

### ISSUE THREAD

**Issue by krzxsiek** [FabioZumbi12/RedProtect#148]
file-type: mysql

`
[11:54:36 INFO]: [AuthMe] krzhu logged in!
[11:54:36 INFO]: Title command successfully executed
[11:54:50 ERROR]: Could not pass event PrepareItemCraftEvent to RedProtect v7.1.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:768) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.CraftingManager.craft(CraftingManager.java:314) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntitySheep.a(EntitySheep.java:273) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntitySheep.b(EntitySheep.java:242) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntitySheep.createChild(EntitySheep.java:290) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.PathfinderGoalBreed.i(PathfinderGoalBreed.java:75) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.PathfinderGoalBreed.e(PathfinderGoalBreed.java:51) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.PathfinderGoalSelector.a(SourceFile:129) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:656) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntityAgeable.n(EntityAgeable.java:158) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntityAnimal.n(EntityAnimal.java:24) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntitySheep.n(EntitySheep.java:68) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1604) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at br.net.fabiozumbi12.RedProtect.listeners.RPPlayerListener.onCraftItem(RPPlayerListener.java:115) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-d4f98a3-cb61ac0]
        ... 28 more`

**Comment by FabioZumbi12** [comment]
Seems you have a "EntitySheep" crafting a item o.O

**Comment by krzxsiek** [comment]
This region only have a pigs :D No sheeps

**Comment by FabioZumbi12** [comment]
But you have a plugin opening a virtual crafting table or similar?

**Comment by krzxsiek** [comment]
i have... CoreProtect, dynmap, WorldEdit, SkinsRestorer, ChopTree3, PermissionsEx,
Bags, Vault, Proctolib, NoCheatPlus, Orebfuscator4, Essentials, EssentialsProtect,
EssentialsChat, EssentislsGeoIP, EssentialsAntiBuild, Jobs, ShopChest, RedProtect,
HolographicDisplays, EssentialsSpawn, CratesPlus, AuthMe, RandomTeleport

**Comment by FabioZumbi12** [comment]
If this error ocurrs sometimes you can leave... theres nothing wrong on code.
