### ISSUE TITLE
MySql  erro again with 6.4.3...

### ISSUE THREAD

**Issue by SmithJiong** [FabioZumbi12/RedProtect#18]
I update the plugins today...and  can not connect database again....
Looks like the new plug-in does not support read data on the old database..
But It did not work even i  create a new shema...

[00:40:31] [Server thread/INFO]: ---------------- RedProtect v6.4.3 ----------------
[00:40:31] [Server thread/INFO]: Developed by [FabioZumbi12].
[00:40:31] [Server thread/INFO]: For more information about the commands, type [/rp ?].
[00:40:31] [Server thread/INFO]: For a tutorial, type [/rp tutorial].
[00:40:31] [Server thread/INFO]: ---------------------------------------------------
[00:40:34] [Server thread/INFO]: [RedProtect] Disabling RedProtect v6.4.3
[00:40:34] [Server thread/INFO]: Redprotect: [RedProtect v6.4.3 disabled.]
[00:40:34] [Server thread/INFO]: [RedProtect] Enabling RedProtect v6.4.3
[00:40:34] [Server thread/INFO]: Redprotect: [Server version: 1.7.10-R0.1-SNAPSHOT]
[00:40:34] [Server thread/INFO]: Redprotect: [All configurations loaded!]
[00:40:34] [Server thread/INFO]: Redprotect: [Language file loaded - Using: ZH-CN]
[00:40:34] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:7145)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.checkDBExists(WorldMySQLRegionManager.java:102)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.<init>(WorldMySQLRegionManager.java:53)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RegionManager.loadAll(RegionManager.java:32)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:98)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RPCommands.onCommand(RPCommands.java:204)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:473)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[00:40:34] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:40:34] [Server thread/WARN]: java.sql.SQLException: Can't create database 'redprotect_world'; database exists
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1662)
[00:40:34] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1581)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.<init>(WorldMySQLRegionManager.java:56)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RegionManager.loadAll(RegionManager.java:32)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:98)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RPCommands.onCommand(RPCommands.java:204)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:473)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[00:40:34] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:40:34] [Server thread/INFO]: Redprotect: [Vault found. Hooked.]
[00:40:34] [Server thread/INFO]: Redprotect: [Essentials found. Hooked.]
[00:40:34] [Server thread/WARN]: java.lang.NullPointerException
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.getTotalRegionNum(WorldMySQLRegionManager.java:599)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RegionManager.getTotalRegionsNum(RegionManager.java:298)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:166)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[00:40:34] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RPCommands.onCommand(RPCommands.java:204)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[00:40:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:473)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[00:40:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[00:40:34] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:40:34] [Server thread/INFO]: Redprotect: [RedProtect Plus reloaded!]

**Comment by FabioZumbi12** [comment]
Yep, a mistake! Fixed on 6.4.3.1 http://dev.bukkit.org/media/files/909/527/RedProtect.jar
