### ISSUE TITLE
Sponge Forge 1.12.1 Latest build. Error.

### ISSUE THREAD

**Issue by Mr-Krab** [FabioZumbi12/RedProtect#209]
The sign does not create a private.

When create a private with a command, this error appears.
 [Sponge]: Error occurred while executing command 'rp claim test Mr_Krab' for source EntityPlayerMP['uppr'/444, l='world', x=-60,80, y=98,03, z=155,61]: null
java.lang.NullPointerException: null
        at br.net.fabiozumbi12.redprotect.RegionManager.getRegion(RegionManager.java:90) ~[RegionManager.class:?]
        at br.net.fabiozumbi12.redprotect.actions.DefineRegionBuilder.<init>(DefineRegionBuilder.java:64) ~[DefineRegionBuilder.class:?]
        at br.net.fabiozumbi12.redprotect.listeners.RPCommands.process(RPCommands.java:1114) ~[RPCommands.class:?]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.1-2480-7.0.0-BETA-2640]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:326) ~[SpongeCommandManager.class:1.12.1-2480-7.0.0-BETA-2640]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:950) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:929) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[la.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:149) ~[PacketUtil.class:1.12.1-2480-7.0.0-BETA-2640]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.12.1-2480-7.0.0-BETA-2640]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:148) [PacketUtil.class:1.12.1-2480-7.0.0-BETA-2640]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkb000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.1-2480-7.0.0-BETA-2640]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zid000(MinecraftServer.java:4013) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by FabioZumbi12** [comment]
Try the latest build and post the error again, but on hastebin, or on any site for logs.

**Comment by Mr-Krab** [comment]
It works, but I see the console spam.
[11:59:09] [Server thread/ERROR] [Sponge]: Could not pass SpawnEntityEvent$ChunkLoad$Impl to Plugin{id=redprotect, name=RedProtect, version=7.3.0, description=Complete antigrief plugin, authors=[FabioZumbi12], source=/root/server/industrial/./plugins/RedProtect-7.3.0-b49-Universal.jar}
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_144]
        at br.net.fabiozumbi12.RedProtect.Sponge.listeners.RPWorldListener.onChunkUnload(RPWorldListener.java:52) ~[RPWorldListener.class:?]
        at org.spongepowered.common.event.listener.ChunkLoadListener_RPWorldListener_onChunkUnload265.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2486-7.0.0-BETA-2653]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.12.2-2486-7.0.0-BETA-2653]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.12.2-2486-7.0.0-BETA-2653]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.12.2-2486-7.0.0-BETA-2653]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.12.2-2486-7.0.0-BETA-2653]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:198) [SpongeImpl.class:1.12.2-2486-7.0.0-BETA-2653]
        at net.minecraft.world.WorldServer.handler$spongeLoadEntities$zkl000(WorldServer.java:2579) [oo.class:?]
        at net.minecraft.world.WorldServer.func_175650_b(WorldServer.java) [oo.class:?]
        at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:857) [axw.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:105) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by FabioZumbi12** [comment]
Try the latest jenkins build, i think is fixed.

**Comment by Mr-Krab** [comment]
Working. If I notice still mistakes I shall inform.
