### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KonoromiHimaries** [FabioZumbi12/RedProtect#211]
timings
https://timings.aikar.co/?id=08f0181676cc4357805bdec25c8e35d5

logs
```
[21:31:49] [Server thread/WARN]: [RedProtect] "RedProtect v7.3.0" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "public void br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPGlobalListener.PlayerPickup(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [FabioZumbi12].
org.bukkit.plugin.AuthorNagException: null
	at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:277) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:545) [patched_1.12.2.jar:git-Paper-1222]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.onEnable(RedProtect.java:124) [RedProtect-7.3.0-b51-Universal.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[21:31:49] [Server thread/WARN]: [RedProtect] "RedProtect v7.3.0" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "public void br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPPlayerListener.PlayerPickup(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [FabioZumbi12].
org.bukkit.plugin.AuthorNagException: null
	at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:277) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:545) [patched_1.12.2.jar:git-Paper-1222]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.onEnable(RedProtect.java:126) [RedProtect-7.3.0-b51-Universal.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by FabioZumbi12** [comment]
Using latest jenkins dev version works? http://areaz12server.net.br:8080/job/RedProtect/
