### ISSUE TITLE
Database problem!

### ISSUE THREAD

**Issue by FabioZumbi12** [FabioZumbi12/RedProtect#22]
Hello Fabio i have a problem with the New 6.5 Version 'destorys' the database each time on loading and fails loadinging the plugin after

After loading i have nonsese like this in the file: Datdas_altes_Dorf: name: Datdas_altes_Dorf lastvisit: 24/11/2015 admins: &id002 - '#server#' members: [] leaders: *id002

maybe this an other problem there? here is the errorlig.. what a luck that we have backups :D

[09:25:27] [Server thread/INFO]: [RedProtect] Enabling RedProtect v6.5.0
[09:25:27] [Server thread/INFO]: Redprotect: [Server version: 1.8.8-R0.1-SNAPSHOT][m
[09:25:28] [Server thread/INFO]: Redprotect: [All configurations loaded!][m
[09:25:28] [Server thread/INFO]: Redprotect: [Language file loaded - Using: DE-DE][m
[09:25:28] [Server thread/INFO]: Redprotect: [PvPManager found. Hooked.][m
[09:25:28] [Server thread/INFO]: Redprotect: [Loaded 57 regions (yml)][m
[09:25:28] [Server thread/INFO]: Redprotect: [[0;33;22mLeader from: #server#[m][m
[09:25:28] [Server thread/INFO]: Redprotect: [[0;33;22mTo UUID: #server#[m][m
[09:25:28] [Server thread/INFO]: Redprotect: [[0;33;22mAdmin from: #server#[m][m
[09:25:28] [Server thread/INFO]: Redprotect: [[0;33;22mTo UUID: #server#[m][m
[09:25:28] [Server thread/INFO]: Redprotect: [[0;32;1m[21m[1]Region updated [0;33;22m[21mDatdas_altes_Dorf[0;32;1m[21m. Leaders [0;33;22m[21m[#server#][m][m
[09:25:28] [Server thread/INFO]: Redprotect: [[0;32;1m[21m[2]Region updated [0;33;22m[21mSpawn[0;32;1m[21m. Leaders [0;33;22m[21m[f24df990-9c6b-4f32-938a-4c91a26d31f4][m][m
[09:25:28] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
[09:25:28] [Server thread/WARN]: 	at java.lang.String.substring(String.java:1931)
[09:25:28] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Region.getLeadersDesc(Region.java:1266)
[09:25:28] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RPUtil.ReadAllDB(RPUtil.java:369)
[09:25:28] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:171)
[09:25:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[09:25:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[09:25:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[09:25:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[09:25:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[09:25:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[09:25:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[09:25:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[09:25:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[09:25:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[09:25:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[09:25:28] [Server thread/INFO]: Redprotect: [[0;31;1m[21mError enabling RedProtect, plugin will shut down.[m][m
[09:25:28] [Server thread/INFO]: Redprotect: [[0;31;1m[21mRedProtect v6.5.0 disabled.[m][m

**Comment by FabioZumbi12** [comment]
Try this version: http://areaz12server.net.br/download/RedProtect.jar

And the "*id002" does break the database, its a yaml issue but dont interfer in nothing to work of plugin.

**Comment by CloudeLecaw** [comment]
Version 6.5.1 fixed the Problem :-)
Thank you!

**Comment by FabioZumbi12** [comment]
Fine ^^
