### ISSUE TITLE
Protection.yml out of date or is it just not working?

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#25]
I get this when the filter try to interact with the protection ofthe chat
i added my protections.yml - like last time with a added .txt so i can upload it
[protections.yml.txt](https://github.com/FabioZumbi12/RedProtect/files/150007/protections.yml.txt)

`[17:46:25] [Netty Epoll Server IO #3/ERROR]: Could not pass event AsyncPlayerChatEvent to RedProtect v6.5.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:237) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at gyurix.spigotlib.features.LongerChat.onPacketIN(LongerChat.java:59) [SpigotLib.jar:?]
	at gyurix.protocol.Protocol.dispatchPacketInEvent(Protocol.java:124) [SpigotLib.jar:?]
	at gyurix.protocol.v1_8.Protocol18$NewChannelHandler.channelRead(Protocol18.java:261) [SpigotLib.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1963) ~[?:1.8.0_60]
	at br.net.fabiozumbi12.RedProtect.listeners.RPAddProtection.onPlayerChat(RPAddProtection.java:160) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	... 31 more`

**Comment by FabioZumbi12** [comment]
Seem to be a problem with word check. I changed the code and i think fix the problem.

**Comment by FabioZumbi12** [comment]
Try this version: http://areaz12server.net.br/download/RedProtect.jar

**Comment by CloudeLecaw** [comment]
[09:20:57 ERROR]: Could not pass event AsyncPlayerChatEvent to RedProtect v6.5.1
org.bukk

**Comment by FabioZumbi12** [comment]
=D
