### ISSUE TITLE
RedProtect incompatible with PVPManager

### ISSUE THREAD

**Issue by FabioZumbi12** [FabioZumbi12/RedProtect#27]
_from Adnurmal:_

http://pastebin.com/RrVkCuav

I installed RedProtect for 1.9 update release, all fired up fine (havent tested yet). After I added PVPManager (premium plugin), the console showed the following and failed to load. 

Please add compatibility, I really wish to use the PVPManager to allow players to turn on and off pvp at anytime.

**Comment by FabioZumbi12** [comment]
What is the version string of your PVPManager?

**Comment by CloudeLecaw** [comment]
im using the Free Version of it...so i cant tell you if this may just happens in the Premium Version?...

in the Free Version all works fine..VersionNumber is:
PvPManager_3.0-Build191 together with Redprotect 6.5.3
For Adnurmal: Pls notices PvPManager Premium also had an Update after 1.9..

**Comment by CloudeLecaw** [comment]
I upgraded to PremiuMVersion of PvP Manager now
and an agree this problem.
here is the errorlog.

`[09:59:12] [Server thread/ERROR]: Error occurred while enabling RedProtect v6.5.4 (Is it up to date?)
java.lang.NoClassDefFoundError: me/NoChance/PvPManager/PvPManager
	at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:137) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.ClassNotFoundException: me.NoChance.PvPManager.PvPManager
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	... 12 more`

**Comment by FabioZumbi12** [comment]
Seems the PVPManager have other clas name!
Can you confirm openning the "plugin.yml" from you pvpmanager premium jar and see this lines:

```
name: PvpManager
main: me/NoChance/PvPManager
```

If is diferent, paste here to i make compatible.

**Comment by CloudeLecaw** [comment]
**Premium: 3.5.7**
name: PvPManager
main: nc.aT
version: 3.5.7
author: NoChanceSD
description: Allows Administrators To Change Their PvP Mechanics.
softdepend: [Vault, WorldGuard, DisguiseCraft, LibsDisguises, Factions, EZRanksLite, Essentials]

**
Free: 3.0 Build 197**
name: PvPManager
main: me.NoChance.PvPManager.PvPManager
version: 3.0-SNAPSHOT-b197
author: NoChanceSD
description: Allows Administrators To Change Their PvP Mechanics.
softdepend: [Vault, WorldGuard, DisguiseCraft, LibsDisguises, Factions, EZRanksLite, Essentials]

**Comment by FabioZumbi12** [comment]
Fixed on latest PvPmanager! Uploading the latest Redprotect to fix.
