### ISSUE TITLE
Hook into plugin...

### ISSUE THREAD

**Issue by MrKiller01** [FabioZumbi12/RedProtect#271]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  7.4.1

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Is it possible to hook into preciousstones? Let PS do what it wants, and next to it running RP without interference from both of them.....
I noticed that when RP was active, i could place a preciousstone, but without its Precious function, rendering it useless....
Is there a way to let them both work together on the same server? If Worldguard is hopefully off the table, because of problems, still some plugins are depending on that. (T)His owner does not respond to my pleas....
I hope you are willing to tackle this problem...

Thanks

**Comment by MrKiller01** [comment]
> [16:05:12 ERROR]: Could not pass event BlockPlaceEvent to PreciousStones v10.7.2

org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlac
eEvent(CraftEventFactory.java:150) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620
]
        at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207)
 [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractM
anager.java:505) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.jav
a:951) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseIt
em.java:37) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseIt
em.java:1) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:
13) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.
12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:
748) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
406) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
679) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/API/Re
dProtectAPI
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuild(RedProtectManager.java:65) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuildField(RedProtectManager.java:90) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.PermissionsManager.
canBuildField(PermissionsManager.java:160) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.a
dd(ForceFieldManager.java:102) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.on
BlockPlace(PSBlockListener.java:740) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        ... 18 more
Caused by: java.lang.ClassNotFoundException: br.net.fabiozumbi12.RedProtect.API.
RedProtectAPI
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:152) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:100) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuild(RedProtectManager.java:65) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuildField(RedProtectManager.java:90) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.PermissionsManager.
canBuildField(PermissionsManager.java:160) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.a
dd(ForceFieldManager.java:102) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.on
BlockPlace(PSBlockListener.java:740) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        ... 18 more

>

**Comment by CloudeLecaw** [comment]
this is RedProtect?
i see nothing in the errorcode that leads to RedProtect...
have u informed the dev of PreciousStones?

**Comment by FabioZumbi12** [comment]
PreciousStones need to update their hook with the latest public (or dev) builds of redprotect. The api changed since 7.3.0.
