### ISSUE TITLE
 Issues about mysql  in V6.5.3

### ISSUE THREAD

**Issue by SmithJiong** [FabioZumbi12/RedProtect#29]
I found the region table had not same Column's  structure between the  newest and older database when i  update the plugin.
So I droped the older table and region new table. But there still was erro message when create new region,like this. 
[09:09:21] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '='%jamessoap%'' at line 1
[09:09:21] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:09:21] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[09:09:21] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[09:09:21] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[09:09:21] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[09:09:21] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[09:09:21] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[09:09:21] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[09:09:21] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[09:09:21] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[09:09:21] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[09:09:21] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[09:09:21] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
[09:09:21] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474)
[09:09:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.getRegions(WorldMySQLRegionManager.java:378)
[09:09:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RegionManager.getRegions(RegionManager.java:118)
[09:09:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.listeners.RPCommands.getRegionforList(RPCommands.java:2293)
[09:09:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.listeners.RPCommands.handleList(RPCommands.java:2286)
[09:09:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.listeners.RPCommands.onCommand(RPCommands.java:1600)
[09:09:21] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[09:09:21] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[09:09:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[09:09:21] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317)
[09:09:21] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099)
[09:09:21] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[09:09:21] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[09:09:21] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[09:09:21] [Server thread/WARN]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[09:09:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[09:09:21] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[09:09:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[09:09:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[09:09:21] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by FabioZumbi12** [comment]
I think this version solves: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5-SNAPSHOT.jar?raw=true

Will be present on 6.5.9

**Comment by FabioZumbi12** [comment]
Think fixed!
