### ISSUE TITLE
GUI make Problems?

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#299]
Whe ni try to execute /rp flag in latest Version i get this error;:

```
> [16:43:35 INFO]: Cloude_Lecaw issued server command: /rp flag
> [16:43:35 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.5.0
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at net.minecraft.server.v1_13_R1.PlayerConnection.chat(PlayerConnection.java:1550) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at org.bukkit.craftbukkit.v1_13_R1.entity.CraftPlayer.chat(CraftPlayer.java:320) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at gyurix.chatcontrol.modules.LongerChat$1.run(LongerChat.java:53) [ChatControl_1.9Pre6.jar:?]
>         at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
> Caused by: java.lang.IllegalArgumentException: Material cannot be null
>         at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:56) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         at br.net.fabiozumbi12.RedProtect.Bukkit.config.RPConfig.getGuiSeparator(RPConfig.java:566) ~[?:?]
>         at br.net.fabiozumbi12.RedProtect.Bukkit.RPGui.<init>(RPGui.java:128) ~[?:?]
>         at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPCommands.onCommand(RPCommands.java:1239) ~[?:?]
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
>         ... 13 more
```

**Comment by CloudeLecaw** [comment]
Also i noticed that when looking inside the files - RedProtect Menues do not show ü ö ä and the others anymore.. just some ugly symbols instead
![image](https://user-images.githubusercontent.com/12080017/43789559-93d7a7f2-9a70-11e8-84ad-0c5eb71e1e5e.png)

**Comment by FabioZumbi12** [comment]
Check for itemnames on your guiconfig.yml and on config.yml. Probally you need to change some of them.

Theres no changes on encoding by redprotect part. Seems something changed on spigot about this. You tried to set the correct chars and reload?

**Comment by CloudeLecaw** [comment]
OK here some Problems i found - New 1.13 Itemnames are the Problem and let the GUI  failing now - was wondering about this because it worked before:
So here are the new names:
old:
  material: THIN_GLASS
    material: WOOD_DOOR
    material: WOOD_BUTTON
    material: SAPLING
    material: DOUBLE_PLANT
```
the most important becuase it was not working is THIN_PLANE this must be changed for 1.13 to
GRAY_STAINED_GLASS_PANE

**Comment by FabioZumbi12** [comment]
Redprotect will not ipdate this to do not overwrite the user customizations. You need to change all based on thats javadocs.

**Comment by FabioZumbi12** [comment]
It is on update note on spigpt xD
