### ISSUE TITLE
[BUG] Problema ao usar mysql na versão para 1.13

### ISSUE THREAD

**Issue by eltonnikecasa** [FabioZumbi12/RedProtect#303]
Platform: Debian 9 Server
                Java 8
Jar version:  RedProtect-7.5.0-b112-Universal.jar
Minecraft version:  spigot-1.13.jar

Description:  Estou tendo problema quando uso MySQL com a versão mais recente do RP. Ele esta lendo as rps antigas que já estão no banco de dados corretamente. Porem quando tento criar novas ele não cria e gera um log de erro no console.

Log Minecraft:

[22:03:54] [Server thread/WARN]: java.sql.SQLException: No value specified for parameter 19
[22:03:54] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[22:03:54] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[22:03:54] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[22:03:54] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[22:03:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2211)
[22:03:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2191)
[22:03:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
[22:03:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[22:03:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[22:03:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[22:03:54] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.WorldMySQLRegionManager.addLiveRegion(WorldMySQLRegionManager.java:166)
[22:03:54] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.WorldMySQLRegionManager.add(WorldMySQLRegionManager.java:137)
[22:03:54] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RegionManager.add(RegionManager.java:184)
[22:03:54] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPBlockListener.onSignPlace(RPBlockListener.java:133)
[22:03:54] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:03:54] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:03:54] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:03:54] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:03:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[22:03:54] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:03:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[22:03:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[22:03:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2377)
[22:03:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.PacketPlayInUpdateSign.a(SourceFile:44)
[22:03:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.PacketPlayInUpdateSign.a(SourceFile:10)
[22:03:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10)
[22:03:54] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:03:54] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:03:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198)
[22:03:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884)
[22:03:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[22:03:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[22:03:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[22:03:54] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by eltonnikecasa** [comment]
hoje baixei a versão, Jar version: RedProtect-7.5.0-b112-Universal.jar, e tive o mesmo problema.

**Comment by eltonnikecasa** [comment]
hoje baixei a versão, Jar version: RedProtect-7.5.0-b114-Universal.jar, e tive o mesmo problema.

**Comment by eltonnikecasa** [comment]
acabei de testar a verão e o problema persiste, Jar version: RedProtect-7.5.0-b116-Universal.jar, e tive o mesmo problema.

**Comment by eltonnikecasa** [comment]
acabei de testar a versão e o problema persiste, Jar version: RedProtect-7.5.0-b117-Universal.jar, e tive o mesmo problema.

[01:05:52 WARN]: java.sql.SQLException: No value specified for parameter 21
[01:05:52 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:05:52 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:05:52 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:05:52 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:05:52 WARN]:        at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2211)
[01:05:52 WARN]:        at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2191)
[01:05:52 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
[01:05:52 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[01:05:52 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[01:05:52 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[01:05:52 WARN]:        at br.net.fabiozumbi12.RedProtect.Bukkit.WorldMySQLRegionManager.addLiveRegion(WorldMySQLRegionManager.java:166)
[01:05:52 WARN]:        at br.net.fabiozumbi12.RedProtect.Bukkit.WorldMySQLRegionManager.add(WorldMySQLRegionManager.java:137)
[01:05:52 WARN]:        at br.net.fabiozumbi12.RedProtect.Bukkit.RegionManager.add(RegionManager.java:184)
[01:05:52 WARN]:        at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPBlockListener.onSignPlace(RPBlockListener.java:133)
[01:05:52 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:52 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:05:52 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:52 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[01:05:52 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[01:05:52 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[01:05:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[01:05:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[01:05:52 WARN]:        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2377)
[01:05:52 WARN]:        at net.minecraft.server.v1_13_R1.PacketPlayInUpdateSign.a(SourceFile:44)
[01:05:52 WARN]:        at net.minecraft.server.v1_13_R1.PacketPlayInUpdateSign.a(SourceFile:10)
[01:05:52 WARN]:        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10)
[01:05:52 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:05:52 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:05:52 WARN]:        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198)
[01:05:52 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884)
[01:05:52 WARN]:        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[01:05:52 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[01:05:52 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[01:05:52 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by eltonnikecasa** [comment]
Bug Fixed Jar version: RedProtect-7.5.0-b119-Universal.jar

Thanks Fabio

**Comment by FabioZumbi12** [comment]
kkk nada ^^
