### ISSUE TITLE
[bug] commando /rp flag não funciona

### ISSUE THREAD

**Issue by eltonnikecasa** [FabioZumbi12/RedProtect#304]
Platform: Debian 9
                Java 8
                Mysql

Jar version:  RedProtect-7.5.0-b115-Universal.jar

Minecraft version: Spigot 1.13  

Problema ao executar o comando /rp flag

[00:02:31 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.5.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: Material cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:56) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        at br.net.fabiozumbi12.RedProtect.Bukkit.config.RPConfig.getGuiSeparator(RPConfig.java:566) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.RPGui.<init>(RPGui.java:128) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPCommands.onCommand(RPCommands.java:1239) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
        ... 15 more

**Comment by FabioZumbi12** [comment]
É porque vc não atualizou os materiais do guiconfig.yml de acordo com o aviso na nota de update do 1.13: https://www.spigotmc.org/resources/redprotect-for-all-versions-anti-grief-server-protection.15841/update?update=238449

**Comment by eltonnikecasa** [comment]
Deletei o arquivo guiconfig.yml, e reiniciei o server. 100% ok

obrigado fabio
