### ISSUE TITLE
/rp border

### ISSUE THREAD

**Issue by AnonymousDr** [FabioZumbi12/RedProtect#33]
The console drop this crash:

[Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v6.5.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_9_R1.block.CraftBlock.setType(CraftBlock.java:123) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.craftbukkit.v1_9_R1.block.CraftBlock.setType(CraftBlock.java:118) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at br.net.fabiozumbi12.RedProtect.RPUtil.addBorder(RPUtil.java:760) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.listeners.RPCommands.onCommand(RPCommands.java:670) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
	... 15 more

**Comment by FabioZumbi12** [comment]
Please, check if the matrial name for border block is correct on configuration.

**Comment by AnonymousDr** [comment]
This problem is fixed.

Thanks.
