### ISSUE TITLE
Little Error on Servershutdown... in new Spigot 1.13.2

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#339]
```
[16:18:28] [Server thread/ERROR]: Error occurred while disabling RedProtect v7.5.4 (Is it up to date?)
java.lang.NullPointerException: null
	at br.net.fabiozumbi12.RedProtect.Bukkit.RegionManager.unloadAll(RegionManager.java:50) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.shutDown(RedProtect.java:249) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.onDisable(RedProtect.java:81) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:363) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:365) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:625) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:770) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

happens with lattest RedProtect Version

**Comment by FabioZumbi12** [comment]
Try the build 126

**Comment by CloudeLecaw** [comment]
i tested it with Build 133 and it seems to be solved :-)
