### ISSUE TITLE
Error in PlayerMovment for build135

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#344]
In lattest Version Build 135 we have this grazzy Error on PlayerMovenmentEvent

```
[18:50:33] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to RedProtect v7.5.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:948) ~[minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) ~[minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPPlayerListener.RegionFlags(RPPlayerListener.java:1540) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPPlayerListener.onPlayerMovement(RPPlayerListener.java:1033) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[minecraft_server.jar:git-Spigot-e4d0c66-1057710]
	... 15 more
```

**Comment by FabioZumbi12** [comment]
This error is caused by the flag `effects` on that region! Revome this flags and add again. probally is broken or without the number of effects level.

**Comment by CloudeLecaw** [comment]
We removed the effects and now the problem is fixed. Thanks for your fast help <3
