### ISSUE TITLE
/rp flag

### ISSUE THREAD

**Issue by iDavid86920** [FabioZumbi12/RedProtect#346]
_Put if is the **Spigot** or **Sponge** version._  
Platform: Paper Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.5-b129-Universal.jar

_Your server Minecraft version_  
Minecraft version:  This server is running Paper version git-Paper-1466 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

_Issue or Suggestion?_  
What you want?:  When i put /rp flag says internal error. The Plugins is in default mode. No modifications.

Log:
```
[23:02:23 INFO]: iDavid86920 issued server command: /rp flag
[23:02:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.5.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1466]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1466]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1466]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.jar:git-Paper-1466]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1466]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1466]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1466]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1466]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1466]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1466]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1466]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1466]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1466]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[patched_1.12.2.jar:git-Paper-1466]
        at br.net.fabiozumbi12.RedProtect.Bukkit.config.RPConfig.getGuiSeparator(RPConfig.java:511) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.RPGui.<init>(RPGui.java:123) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPCommands.onCommand(RPCommands.java:1233) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1466]
        ... 15 more
```

**Comment by FabioZumbi12** [comment]
This is because you need to change the item in your guiconfig.yml for `gui-separator`
