### ISSUE TITLE
Error on Creating SubZones and Zones (define and claim)

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#347]
in latest RP Version (Build 136)

**_On trying to Create/define a SubZone:_**
```
[10:26:47] [Server thread/INFO]: Cloude_Lecaw issued server command: /rp define Spawn2Test
[10:26:47] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.5.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at br.net.fabiozumbi12.RedProtect.Bukkit.Region.conformName(Region.java:507) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.Region.<init>(Region.java:717) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.actions.DefineRegionBuilder.<init>(DefineRegionBuilder.java:62) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPCommands.onCommand(RPCommands.java:1319) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	... 15 more
```

**On trying to create/define a Zone:**
```
[10:31:49] [Server thread/INFO]: Cloude_Lecaw issued server command: /rp define Spawn2Test
[10:31:49] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.5.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
```

using
- Spigot: 1.13.2 - (one day old compile)
- RedProtect_7.5.5-Build136

same hapens when i try to use /rp Claim...

Note:
The Error exist in:
- RedProtect_7.5.5-Build136
- RedProtect_7.5.5-Build135

The Error does not exists until:
- RedProtect_7.5.5-Build134 <- this is the last working version

**Comment by CloudeLecaw** [comment]
well the same problem can be found here #345

**Comment by FabioZumbi12** [comment]
Try the latest version.

**Comment by CloudeLecaw** [comment]
solved :)
