### ISSUE TITLE
[BUG] ERRO ao criar rp com placa

### ISSUE THREAD

**Issue by eltonnikecasa** [FabioZumbi12/RedProtect#349]
Versão:
RedProtect-7.5.5-b136-Universal.jar

Server:
paperclip-437.jar
Debian 9
Java 8

Erro Log:

[22:26:20 ERROR]: Could not pass event SignChangeEvent to RedProtect v7.5.5
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
        at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelection(WEListener.java:37) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelectionRP(WEListener.java:49) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.actions.EncompassRegionBuilder.<init>(EncompassRegionBuilder.java:322) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPBlockListener.onSignPlace(RPBlockListener.java:127) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor487.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-435]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-435]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-435]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-435]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2522) ~[patched_1.13.2.jar:git-Paper-435]
        at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.13.2.jar:git-Paper-435]
        at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-435]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-435]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-435]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-435]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-435]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-435]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-435]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by FabioZumbi12** [comment]
Atualiza pra ultima versão do worldedit 7.0 ou desliga a integração com worldedit  no config.yml do redprotect.
