### ISSUE TITLE
Error with kcauldron version 1.7.10

### ISSUE THREAD

**Issue by brutalzinn** [FabioZumbi12/RedProtect#355]
Could not pass event SignChangeEvent to RedProtect v6.4.0

```
Could not pass event SignChangeEvent to RedProtect v6.4.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1448.121]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1448.121]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1448.121]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1448.121]
    at net.minecraft.network.NetHandlerPlayServer.func_147343_a(NetHandlerPlayServer.java:2294) [nh.class:?]
    at net.minecraft.network.play.client.C12PacketUpdateSign.func_148833_a(SourceFile:48) [jn.class:?]
    at net.minecraft.network.play.client.C12PacketUpdateSign.func_148833_a(SourceFile:9) [jn.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
    at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.getRegions(WorldMySQLRegionManager.java:185) ~[?:?]
    at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.getTotalRegionSize(WorldMySQLRegionManager.java:392) ~[?:?]
    at br.net.fabiozumbi12.RedProtect.RegionManager.getTotalRegionSize(RegionManager.java:86) ~[?:?]
    at br.net.fabiozumbi12.RedProtect.EncompassRegionBuilder.<init>(EncompassRegionBuilder.java:186) ~[?:?]
    at br.net.fabiozumbi12.RedProtect.listeners.RPBlockListener.onSignPlace(RPBlockListener.java:136) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1448.121]
    ... 13 more
```

This error only happens when I try to use mysql as database. Please help me. This plugin is wonderful.

**Comment by brutalzinn** [comment]
I'm using kcoulderon
 1.7.10

**Comment by brutalzinn** [comment]
And version 6.4.0 is the only one that works for me, because the other versions ... the plugin does not work, it always generates the error sing could not pass ... and the plugin just does not work.

**Comment by FabioZumbi12** [comment]
Download the latest from our jenkins, its 90% compatible with kcauldron (the other 10 is not teste by me).

**Comment by brutalzinn** [comment]
Hello Friend. I continue with the error could not pass sign.Event ... The plugin does not seem to work on my server, because even after doing what you recommended to me, the plugin simply does not obey even the commands. And there is no log in the red protect folder. Can you help me?

**Comment by brutalzinn** [comment]
Você é brasileiro? Se for, eu continuo com o mesmo problema no plugin. Já tentei todas as versões do repositório que você me recomendou baixar, mas não funciona. Em nenhum deles os comandos funcionam, e sempre aparece o error could not pass sign event... quando tento colocar uma placa. Pode me ajudar?

- Grato

**Comment by FabioZumbi12** [comment]
Probally theres some errors on server start logs.

**Comment by brutalzinn** [comment]
```
[12:34:16] [Server thread/ERROR]: Error occurred while enabling RedProtect v7.4.1 (Is it up to date?)
java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/Bukkit/WorldFlatFileRegionManager
	at br.net.fabiozumbi12.RedProtect.Bukkit.RegionManager.load(RegionManager.java:41) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RegionManager.loadAll(RegionManager.java:29) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:256) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.onEnable(RedProtect.java:120) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1448.121]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1448.121]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1448.121]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: Failed to remap class br.net.fabiozumbi12.RedProtect.Bukkit.WorldFlatFileRegionManager
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1448.121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	... 15 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:453) ~[PluginClassLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1448.121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	... 15 more
[12:34:16] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.2.2-SNAPSHOT;8eeab68
[12:34:17] [Server thread/ERROR]: Error occurred while enabling WorldGuard v6.2.2-SNAPSHOT;8eeab68 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.maximumSize(J)Lguava10/com/google/common/cache/CacheBuilder;
	at com.sk89q.worldguard.session.SessionManager.<init>(SessionManager.java:60) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:160) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1448.121]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1448.121]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1448.121]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[12:34:17] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:34:17] [Server thread/INFO]: Done (47.870s)! For help, type "help" or "?"
[12:34:17] [Server thread/INFO]: Registered command forge with permission node net.minecraftforge.server.command.ForgeCommand
[12:34:18] [Server thread/INFO]: Registered command ic2 with permission node ic2.core.command.CommandIc2
[12:34:18] [Server thread/INFO]: Registered command tps with permission node ic2.core.command.CommandTps
[12:34:18] [Server thread/INFO]: Registered command ae2 with permission node appeng.server.AECommand
[12:34:18] [Server thread/INFO]: Registered command buildcraft with permission node buildcraft.core.lib.commands.RootCommand
[12:34:18] [Server thread/WARN]: ############################################
[12:34:18] [Server thread/WARN]: #                                          #
[12:34:18] [Server thread/WARN]: #  Cauldron has been detected! Please keep #
[12:34:18] [Server thread/WARN]: #  in mind that BuildCraft may NOT provide #
[12:34:18] [Server thread/WARN]: # support to Cauldron users, as the mod is #
[12:34:18] [Server thread/WARN]: # primarily tested without Bukkit/Spigot's #
[12:34:18] [Server thread/WARN]: #    changes to the Minecraft internals.   #
[12:34:18] [Server thread/WARN]: #                                          #
[12:34:18] [Server thread/WARN]: #  Any lag caused by BuildCraft on top of  #
[12:34:18] [Server thread/WARN]: #  Cauldron likely arises from workarounds #
[12:34:18] [Server thread/WARN]: #  which we apply to make sure BuildCraft  #
[12:34:18] [Server thread/WARN]: #  works properly with Cauldron installed. #
[12:34:18] [Server thread/WARN]: #                                          #
[12:34:18] [Server thread/WARN]: #     Thanks for your attention! ~ BC devs #
[12:34:18] [Server thread/WARN]: #                                          #
[12:34:18] [Server thread/WARN]: ############################################
[12:34:18] [Server thread/INFO]: Registered command ie with permission node blusunrize.immersiveengineering.common.util.commands.CommandHandler
[12:34:18] [Server thread/INFO]: Registered command iis with permission node unwrittenfun.minecraft.immersiveintegration.special.SpecialCommand
[12:34:18] [Server thread/INFO]: WorldData loading
[12:34:18] [Server thread/INFO]: WorldData retrieved
[12:34:18] [Server thread/INFO]: Removed 0 old recipes
[12:34:18] [Server thread/INFO]: Starting recipe profiler for Arc Recycling, using 4 Threads
[12:34:19] [Server thread/INFO]: Couldn't fully analyze 1xitem.desertChest@0, missing knowledge for [1xitem.wandererChest@0]
[12:34:19] [Server thread/INFO]: Couldn't fully analyze 1xitem.desertBoots@0, missing knowledge for [1xitem.wandererBoots@0]
[12:34:19] [Server thread/INFO]: Couldn't fully analyze 1xitem.desertLegs@0, missing knowledge for [1xitem.wandererLegs@0]
[12:34:19] [Server thread/INFO]: Couldn't fully analyze 1xitem.desertHelmet@0, missing knowledge for [1xitem.wandererHelmet@0]
[12:34:19] [Server thread/INFO]: Finished recipe profiler for Arc Recycling, took 535 milliseconds
[12:34:19] [Craft Scheduler Thread - 0/INFO]: [Vault] Checking for Updates ... 
[12:34:21] [Craft Scheduler Thread - 0/INFO]: [Vault] No new version available

Eu desabilitei o hook com o world edit.
```

**Comment by brutalzinn** [comment]
> Probally theres some errors on server start logs.

[12:34:16] [Server thread/ERROR]: Error occurred while enabling RedProtect v7.4.1 (Is it up to date?)
java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/Bukkit/WorldFlatFileRegionManager
	at br.net.fabiozumbi12.RedProtect.Bukkit.RegionManager.load(RegionManager.java:41) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RegionManager.loadAll(RegionManager.java:29) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:256) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.onEnable(RedProtect.java:120) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1448.121]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1448.121]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1448.121]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: Failed to remap class br.net.fabiozumbi12.RedProtect.Bukkit.WorldFlatFileRegionManager
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1448.121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	... 15 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:453) ~[PluginClassLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1448.121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	... 15 more
[12:34:16] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.2.2-SNAPSHOT;8eeab68
[12:34:17] [Server thread/ERROR]: Error occurred while enabling WorldGuard v6.2.2-SNAPSHOT;8eeab68 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.maximumSize(J)Lguava10/com/google/common/cache/CacheBuilder;
	at com.sk89q.worldguard.session.SessionManager.<init>(SessionManager.java:60) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:160) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.121]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.121]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1448.121]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1448.121]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1448.121]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[12:34:17] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:34:17] [Server thread/INFO]: Done (47.870s)! For help, type "help" or "?"
[12:34:17] [Server thread/INFO]: Registered command forge with permission node net.minecraftforge.server.command.ForgeCommand
[12:34:18] [Server thread/INFO]: Registered command ic2 with permission node ic2.core.command.CommandIc2
[12:34:18] [Server thread/INFO]: Registered command tps with permission node ic2.core.command.CommandTps
[12:34:18] [Server thread/INFO]: Registered command ae2 with permission node appeng.server.AECommand
[12:34:18] [Server thread/INFO]: Registered command buildcraft with permission node buildcraft.core.lib.commands.RootCommand
[12:34:18] [Server thread/WARN]: ############################################
[12:34:18] [Server thread/WARN]: #                                          #
[12:34:18] [Server thread/WARN]: #  Cauldron has been detected! Please keep #
[12:34:18] [Server thread/WARN]: #  in mind that BuildCraft may NOT provide #
[12:34:18] [Server thread/WARN]: # support to Cauldron users, as the mod is #
[12:34:18] [Server thread/WARN]: # primarily tested without Bukkit/Spigot's #
[12:34:18] [Server thread/WARN]: #    changes to the Minecraft internals.   #
[12:34:18] [Server thread/WARN]: #                                          #
[12:34:18] [Server thread/WARN]: #  Any lag caused by BuildCraft on top of  #
[12:34:18] [Server thread/WARN]: #  Cauldron likely arises from workarounds #
[12:34:18] [Server thread/WARN]: #  which we apply to make sure BuildCraft  #
[12:34:18] [Server thread/WARN]: #  works properly with Cauldron installed. #
[12:34:18] [Server thread/WARN]: #                                          #
[12:34:18] [Server thread/WARN]: #     Thanks for your attention! ~ BC devs #
[12:34:18] [Server thread/WARN]: #                                          #
[12:34:18] [Server thread/WARN]: ############################################
[12:34:18] [Server thread/INFO]: Registered command ie with permission node blusunrize.immersiveengineering.common.util.commands.CommandHandler
[12:34:18] [Server thread/INFO]: Registered command iis with permission node unwrittenfun.minecraft.immersiveintegration.special.SpecialCommand
[12:34:18] [Server thread/INFO]: WorldData loading
[12:34:18] [Server thread/INFO]: WorldData retrieved
[12:34:18] [Server thread/INFO]: Removed 0 old recipes
[12:34:18] [Server thread/INFO]: Starting recipe profiler for Arc Recycling, using 4 Threads
[12:34:19] [Server thread/INFO]: Couldn't fully analyze 1xitem.desertChest@0, missing knowledge for [1xitem.wandererChest@0]
[12:34:19] [Server thread/INFO]: Couldn't fully analyze 1xitem.desertBoots@0, missing knowledge for [1xitem.wandererBoots@0]
[12:34:19] [Server thread/INFO]: Couldn't fully analyze 1xitem.desertLegs@0, missing knowledge for [1xitem.wandererLegs@0]
[12:34:19] [Server thread/INFO]: Couldn't fully analyze 1xitem.desertHelmet@0, missing knowledge for [1xitem.wandererHelmet@0]
[12:34:19] [Server thread/INFO]: Finished recipe profiler for Arc Recycling, took 535 milliseconds
[12:34:19] [Craft Scheduler Thread - 0/INFO]: [Vault] Checking for Updates ... 
[12:34:21] [Craft Scheduler Thread - 0/INFO]: [Vault] No new version available

Eu desabilitei o hook com o world edit.

**Comment by FabioZumbi12** [comment]
#356
