### ISSUE TITLE
I'm still in error. I have already downloaded almost all versions of the plugin at jenkins

### ISSUE THREAD

**Issue by brutalzinn** [FabioZumbi12/RedProtect#356]
Hello Friend. I continue with the error could not pass sign.Event ... The plugin does not seem to work on my server, because even after doing what you recommended to me, the plugin simply does not obey even the commands. And there is no log in the red protect folder. Can you help me?
```
[11:20:07] [Server thread/ERROR]: Could not pass event SignChangeEvent to RedProtect v7.5.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1448.121]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1448.121]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1448.121]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1448.121]
	at net.minecraft.network.NetHandlerPlayServer.func_147343_a(NetHandlerPlayServer.java:2294) [nh.class:?]
	at net.minecraft.network.play.client.C12PacketUpdateSign.func_148833_a(SourceFile:48) [jn.class:?]
	at net.minecraft.network.play.client.C12PacketUpdateSign.func_148833_a(SourceFile:9) [jn.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at br.net.fabiozumbi12.RedProtect.Bukkit.RegionManager.getRegion(RegionManager.java:76) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RPUtil.nameGen(RPUtil.java:262) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.actions.EncompassRegionBuilder.<init>(EncompassRegionBuilder.java:54) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPBlockListener.onSignPlace(RPBlockListener.java:127) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1448.121]
	... 13 more
```

**Comment by brutalzinn** [comment]
Is there any chance you can give me support? I really need this plugin.

**Comment by FabioZumbi12** [comment]
The problem is the java version on your host/machine. Need to be on java 1.8 or the plugin will not work.

**Comment by brutalzinn** [comment]
I keep getting the error

this is the java print:  https://ibb.co/VTn75JC
