### ISSUE TITLE
Hand-held bottle circle to report errors

### ISSUE THREAD

**Issue by shanklm** [FabioZumbi12/RedProtect#363]
_Your server Minecraft version_  
Minecraft version:  1.13.2

_Issue or Suggestion?_  
What you want?:  

> 
[00:17:44] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EpicCraftingsPlus v4.2.3
java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.<init>(II)V
	at ecp.ajneb97.otros.UtilidadesCrafteos.getStack(UtilidadesCrafteos.java:341) ~[?:?]
	at ecp.ajneb97.events.ClickItem.getItem(ClickItem.java:45) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-481]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-481]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-481]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-481]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315) ~[patched_1.13.2.jar:git-Paper-481]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:282) ~[patched_1.13.2.jar:git-Paper-481]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:278) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1390) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-481]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-481]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
>

**Comment by VaiTon** [comment]
I guess it's related to EpicCraftingsPlus more than it is to this plugin, so you should post it on the plugin page/issue tracker.

**Comment by shanklm** [comment]
Sorry, this is a wrong log.
s
