### ISSUE TITLE
有个错误！

### ISSUE THREAD

**Issue by shanklm** [FabioZumbi12/RedProtect#364]
V:1.13.2
[02:55:21] [Server thread/ERROR]: Could not pass event SignChangeEvent to RedProtect v7.5.5
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelection(WEListener.java:36) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelectionRP(WEListener.java:48) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.actions.EncompassRegionBuilder.<init>(EncompassRegionBuilder.java:322) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPBlockListener.onSignPlace(RPBlockListener.java:127) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor633.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-481]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-481]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-481]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2543) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-481]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-481]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-481]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

**Comment by VaiTon** [comment]
Is WorldEdit in the plugin folder with the plugin jar?

**Comment by shanklm** [comment]
> Is WorldEdit in the plugin folder with the plugin jar?

worldedit-bukkit-7.0.0-beta-04.jar
I just deleted worldedit.
Then tested it!
It works fine!
Deleting worldedit is a regrettable question!
Waiting for a long time, thank you for your reply.

From Baidu translation!
