### ISSUE TITLE
Protection don`t work.

### ISSUE THREAD

**Issue by baxandrei** [FabioZumbi12/RedProtect#390]
_Put if is the **Spigot** or **Sponge** version._  
Platform: git-Spigot-3cb9dcb-77ca7ca (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.5-b129-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.13.2

_Issue or Suggestion?_  
What you want?:  Issue

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  I created an sign to protect my area, everyone can break my house.
```
[19:53:15 ERROR]: Could not pass event SignChangeEvent to RedProtect v7.5.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) ~[server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) ~[server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2370) ~[server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelection(WEListener.java:36) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelectionRP(WEListener.java:48) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.actions.EncompassRegionBuilder.<init>(EncompassRegionBuilder.java:322) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPBlockListener.onSignPlace(RPBlockListener.java:127) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[server.jar:git-Spigot-3cb9dcb-77ca7ca]
	... 15 more
```
EDIT: I`m ussing worldedit-bukkit-7.0.0-beta-05

**Comment by FabioZumbi12** [comment]
You need to update redprotect too. Use ou dev build from our jenkins in this page, on home descripition.

**Comment by baxandrei** [comment]
Thanx.
