### ISSUE TITLE
Unhandled exception executing command 'rp' in plugin

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#395]
Spigot-Version: **CraftBukkit version git-Spigot-e6eb36f-d3ed151 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

RP-Version:**RedProtect-7.5.6-bb149-Universal.jar**

**In the latest version you can no longer run zones with /rp redefine!!!
Please fix, thank you very much**

```
[21:27:39] [Server thread/INFO]: Blueeyestar issued server command: /rp redefine testzone
[21:27:39] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.5.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_201]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_201]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_201]
	at br.net.fabiozumbi12.RedProtect.Bukkit.WorldFlatFileRegionManager.getInnerRegions(WorldFlatFileRegionManager.java:290) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.RegionManager.getInnerRegions(RegionManager.java:243) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.actions.RedefineRegionBuilder.<init>(RedefineRegionBuilder.java:106) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPCommands.onCommand(RPCommands.java:2471) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	... 15 more```

**Comment by FabioZumbi12** [comment]
@VaiTon This issue includes your performance changes using chunks https://github.com/FabioZumbi12/RedProtect/blob/master/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/WorldFlatFileRegionManager.java#L290

**Comment by FabioZumbi12** [comment]
Fixed on latest dev builds!
