### ISSUE TITLE
Received This Error

### ISSUE THREAD

**Issue by RogueCmdr** [FabioZumbi12/RedProtect#4]
Just got this error when I ran /rp list Also it says "an internal error occured while attempting to perform this command"

[21:21:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v5.4.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_51]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_51]
Caused by: java.lang.NullPointerException
	at br.net.fabiozumbi12.RedProtect.WorldFlatFileRegionManager.getRegions(WorldFlatFileRegionManager.java:70) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RegionManager.getRegions(RegionManager.java:97) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RPCommands.getRegionforList(RPCommands.java:1553) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RPCommands.handleList(RPCommands.java:1543) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RPCommands.onCommand(RPCommands.java:1053) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	... 15 more

**Comment by RogueCmdr** [comment]
Also this happened when attempting to make a region with the fence

[22:17:55] [Server thread/ERROR]: Could not pass event SignChangeEvent to RedProtect v5.4.7
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1837) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PacketPlayInUpdateSign.a(SourceFile:49) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PacketPlayInUpdateSign.a(SourceFile:11) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_51]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_51]
Caused by: java.lang.NullPointerException
	at br.net.fabiozumbi12.RedProtect.WorldFlatFileRegionManager.getRegions(WorldFlatFileRegionManager.java:70) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RegionManager.getRegions(RegionManager.java:116) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.EncompassRegionBuilder.<init>(EncompassRegionBuilder.java:205) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RPBlockListener.onSignChange(RPBlockListener.java:101) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.8.7_f928e7a-e91aed8.jar:git-Spigot-f928e7a-e91aed8]
	... 15 more

**Comment by FabioZumbi12** [comment]
This two errors seems be the region has a null or invalid creator! If you is using only /rp list, open the <world>.yml and check your region looking for a creator with any information or null...

I will release a new version today... try this too!

**Comment by FabioZumbi12** [comment]
Solved? You checked if the creator is null your file?
