### ISSUE TITLE
[BUG] Create claim error (WorldEdit)

### ISSUE THREAD

**Issue by DakirDEV** [FabioZumbi12/RedProtect#407]
If a user wants to create a claim and sets the sign, the message from screen 1 comes in the chat and the error below comes in the console. 
What is my problem, I don't know how to fix it. Do I have a wrong WorldEdit or Fast Async WorldEdit version?

**Screenshots and LOGs**
Screen 1: http://prntscr.com/n159bb
Screen 2: http://prntscr.com/n15dy5

**ERROR:**
`[20:42:02 ERROR]: Could not pass event SignChangeEvent to RedProtect v7.5.6
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelection(WEListener.java:64) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelectionRP(WEListener.java:76) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.actions.EncompassRegionBuilder.<init>(EncompassRegionBuilder.java:342) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPBlockListener.onSignPlace(RPBlockListener.java:150) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor262.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1589]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1589]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1589]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1589]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2233) ~[patched_1.12.2.jar:git-Paper-1589]
at net.minecraft.server.v1_12_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.12.2.jar:git-Paper-1589]
at net.minecraft.server.v1_12_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1589]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1589]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1589]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1589]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1589]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1589]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1589]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]`

**Server and plugins versions:**
 - Server: PaperSpigot 1.12.2
 - Plugin Version: RedProtect-7.5.6-b154-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
Yep, use the latest version of worldedit 7.0 or disable wecui on hooks section on rp config file.

**Comment by DakirDEV** [comment]
Ok thx 👍

**Comment by Jecvay** [comment]
on sponge server where to find WE 7.0 ?

**Comment by FabioZumbi12** [comment]
I think you will need to disable wecui for sponge for now!
