### ISSUE TITLE
Error on /rp define? V4.5.7

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#41]
i use the glass.
marked spot 1
marked spot 2
and did /rp define
and get this erro mesage:
```
[04:46:44] [Server thread/INFO]: Cloude_Lecaw issued server command: /rp define spawn
[04:46:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v6.5.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.RuntimeException: Getting effective permissions is not yet supported
	at gyurix.ultimateperms.UltimatePermissible.getEffectivePermissions(UltimatePermissible.java:129) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftHumanEntity.getEffectivePermissions(CraftHumanEntity.java:146) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	at br.net.fabiozumbi12.RedProtect.RPPermissionHandler.ClaimLimitHandler(RPPermissionHandler.java:77) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RPPermissionHandler.getPlayerClaimLimit(RPPermissionHandler.java:50) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.DefineRegionBuilder.<init>(DefineRegionBuilder.java:76) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.listeners.RPCommands.onCommand(RPCommands.java:919) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-22dcde5]
	... 15 more
```

**Comment by FabioZumbi12** [comment]
Seems to be a problem when the perms plugin of gyurix try to get the perm of the player.
On line 77 where the error log drops on my code its a Server method, and not by my plugin.

![Line 77](http://i.imgur.com/MPFKgU2.png)

"p.getEffectivePermissions()" is a server method. The error comes when my plugin try to get the permissions of player to run the command.

**Comment by FabioZumbi12** [comment]
Not a RedProtect problem.
