### ISSUE TITLE
[Suggestion] Please don't use javafx.util.Pair

### ISSUE THREAD

**Issue by BaronyCraft** [FabioZumbi12/RedProtect#415]
With commit c3676973d19458854c7b2730d922e01d18302b55, javafx.util.Pair was introduced into several classes,

This is a problem because Oracle's server jre (https://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html) does not include the javafx package. Which means, that as soon as one of those classes is used, the server will throw a ClassNotFoundException. 

**Is your feature request related to a problem? Please describe.**
The server will start normally (if the RP configuration is empty), but as soon as a player
tries to claim an area, they'll get an internal error message.

**Describe the solution you'd like**
Build an implementation of Pair somewhere in RedProtect itself, which can be used instead of javafx.util.pair. In some cases, using a Map, using Map.put instead of new Pair(), and using Map.Entry (which has the same getKey and getValue methods that Pair has) when retrieving a Pair, could work as well. 

**Describe alternatives you've considered**
Not use the server jre. Or pull the jfxrt.jar from the desktop jre or jdk, and put it into the server jre's libaries folder. However, asking a public MineCraft hoster to mess with their JRE installation will, in most cases, not be received well.

**Additional context**

`org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.6.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-614]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-614]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-614]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1782) ~[patched_1.13.2.jar:git-Paper-614]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590) ~[patched_1.13.2.jar:git-Paper-614]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-614]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-614]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-614]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-614]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-614]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-614]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-614]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-614]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: javafx/util/Pair
        at br.net.fabiozumbi12.RedProtect.Bukkit.Region.<init>(Region.java:281) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.actions.DefineRegionBuilder.<init>(DefineRegionBuilder.java:90) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.ClaimCommand.onCommand(ClaimCommand.java:72) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:160) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-614]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[patched_1.13.2.jar:git-Paper-614]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-614]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
        at br.net.fabiozumbi12.RedProtect.Bukkit.Region.<init>(Region.java:281) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.actions.DefineRegionBuilder.<init>(DefineRegionBuilder.java:90) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.ClaimCommand.onCommand(ClaimCommand.java:72) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:160) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-614]
        ... 15 more
`

**Comment by FabioZumbi12** [comment]
Makes sense, i will use my own classes, thanks ;)

**Comment by FabioZumbi12** [comment]
Done on last updates ;)
