### ISSUE TITLE
[BUG] Hooks loaded too early.

### ISSUE THREAD

**Issue by yariplus** [FabioZumbi12/RedProtect#419]
Heyo! Some hooks (dynmap) require the RegionManager to be loaded first.

**To Reproduce**
1. Load any version after e297461925c7c934b2729344d7f2d17e77d1a342 with dynmap.
2. NPE!

```
[RedProtect]: Dynmap found. Hooked.
[RedProtect]: Loading dynmapHook markers...
java.lang.NullPointerException
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.getRegionsByWorld(RegionManager.java:408)
at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:65)
at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooks(HooksManager.java:98)
at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:170)
at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.onEnable(RedProtect.java:93)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
at java.base/java.lang.Thread.run(Thread.java:844)
[RedProtect]: Error enabling RedProtect, plugin will shut down.
```

**Server and plugins versions:**
 - Server: Spigot 1.13.2
 - Plugin Version: B#1​83
 - Java Version: 8

**Comment by FabioZumbi12** [comment]
On truth, its a mistake on Plugin.yml where the IDE have renamed to dynmapHook. Just rename to `dynmap` and will fix. I'ii fix this on next dev build.

**Comment by yariplus** [comment]
No dice here, still getting the same error on 184

**Comment by FabioZumbi12** [comment]
Try `dynmap` in lowercase.

**Comment by yariplus** [comment]
Same thing.

I'm fairly certain https://github.com/FabioZumbi12/RedProtect/blob/master/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/RedProtect.java#L170 just needs to be below the try block.

**Comment by FabioZumbi12** [comment]
I had to open a test server and you are right. The last build fixes xD
Thanks.
