### ISSUE TITLE
[BUG] Little Error on Laoding with dynmap

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#424]
This error apears with:
RedProtect-7.6.0-Build176
Dynmap_3.0-Beta3
Spigot 1.14.pre5

Maybe the error is causes by dynmap not beeing 100% working on current 1.14?

[22:49:22] [Server thread/INFO]: [RedProtect] Loading dynmap markers...[m
[22:49:22] [Server thread/WARN]: java.lang.NullPointerException
[22:49:22] [Server thread/WARN]: 	at org.dynmap.bukkit.DynmapPlugin.getMarkerAPI(DynmapPlugin.java:968)
[22:49:22] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.RPDynmap.<init>(RPDynmap.java:50)
[22:49:22] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.registerHooks(RedProtect.java:242)
[22:49:22] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:291)
[22:49:22] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.onEnable(RedProtect.java:125)
[22:49:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[22:49:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:346)
[22:49:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408)
[22:49:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
[22:49:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
[22:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:439)
[22:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[22:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:749)
[22:49:22] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by VaiTon** [comment]
@CloudeLecaw Is Dynmap installed in your server?

**Comment by VaiTon** [comment]
Maybe it could be. As this issue says (https://github.com/webbukkit/dynmap/issues/2469) the Dynmap plugin doesn't really support 1.14 yet.

**Comment by FabioZumbi12** [comment]
Yeah, and then, dynmap is present but not loaded, this is why Redprotect is dropping this error.
