### ISSUE TITLE
Inventory Click Event needs an Update in Spigot 1.14

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#425]
Redprotec Version: RedProtect-7.6.0-Build189
Spigot Version : 1.14

In new Spigot 1.14 all plugins with a GUI are effecvted by this error.
Ingame you can move and take out the GUI items.

in Console you get this error:

`[22:08:12] [Server thread/ERROR]: Could not pass event InventoryClickEvent to RedProtect v7.6.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) ~[spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) ~[spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2159) ~[spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle()Ljava/lang/String;
	at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RPGui.onInventoryClick(RPGui.java:207) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:311) ~[spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	... 17 more`

**Comment by Blueeyestar** [comment]
I'm afraid we have that problem too. I would be happy if it is managed to fix.

**Comment by FabioZumbi12** [comment]
Fixed on https://github.com/FabioZumbi12/RedProtect/commit/f1b85f1cf0775f36a69145e1c7d7d3d492071f9b
