### ISSUE TITLE
[BUG] Unhandled exception executing command 

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#426]
Spigot-Version: **CraftBukkit version git-Spigot-47463c2-6de3aa1 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)**

Red-Protec-version: **RedProtect-7.6.0-b190-Universal**

_Unfortunately there is a bug with the new version_

[05:46:22] [Server thread/INFO]: Blueeyestar issued server command: /rp flag
[05:46:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:145) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1667) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1507) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:868) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RPGui.<init>(RPGui.java:113) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.FlagCommand.onCommand(FlagCommand.java:62) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:158) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	... 17 more

**Comment by FabioZumbi12** [comment]
I had no problems! Btw use this version with some lines splitted to better debug.
[RedProtect-7.6.0-b${BUILD_NUMBER}-Universal.zip](https://github.com/FabioZumbi12/RedProtect/files/3124579/RedProtect-7.6.0-b.BUILD_NUMBER.-Universal.zip)

**Comment by Blueeyestar** [comment]
https://pastebin.com/vxQxRBVv

**Comment by FabioZumbi12** [comment]
The seems to be related with invalid materials. Check this and try the latest dev build.

**Comment by CloudeLecaw** [comment]
i also had this problem with my old flag gui. in my case it was the name of materials too. look like they changed some names aggain for 1.14 :3

**Comment by thomas-worm** [comment]
Hello,
I have same problem. I found out, that this problem occurs in regions which have the dynmap or the pvparena flag set. If this flags are not in the .yml file of the region the GUI opens.
The Material names in the guiconfig.conf are all correct.

**Comment by FabioZumbi12** [comment]
Should be fixed on latests dev build where rp handle the langs better. (but you still need to set the correct materials on gui)

**Comment by Blueeyestar** [comment]
which one's wrong?

https://pastebin.com/2KgbcbWg

**Comment by Blueeyestar** [comment]
I've been sitting there for 10 hours now not getting /rp flag to run. It has never been so problematic. We checked all materials. All is correct. We also had completely new gui generated, without success.

**Comment by FabioZumbi12** [comment]
Download the latest and paste the new errors logs here again!

**Comment by Blueeyestar** [comment]
the newest file with the current build:  https://pastebin.com/D2y0x4EY

And here are the data..maybe someone will find the problem we are helpless


[RP.zip](https://github.com/FabioZumbi12/RedProtect/files/3125545/RP.zip)

**Comment by Blueeyestar** [comment]
i have vault on it but there are still problems in the console with the file

[00:20:37] [Server thread/INFO]: [ShopChest] Enabling ShopChest v1.13-SNAPSHOT
[00:20:37] [Server thread/ERROR]: [ShopChest] Could not find any Vault economy dependency!
[00:20:37] [Server thread/INFO]: [ShopChest] Disabling ShopChest v1.13-SNAPSHOT
[00:20:37] [Server thread/ERROR]: Error occurred while disabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at de.epiceric.shopchest.ShopChest.onDisable(ShopChest.java:216) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:370) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:150) [ShopChest-1.13-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:346) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by FabioZumbi12** [comment]
Its worked fine here too with your configs :/
![image](https://user-images.githubusercontent.com/5833818/56870863-0cd51400-69ec-11e9-8b7b-2d146656490c.png)
Create a new region and try to use the rp flag in there!

**Comment by Blueeyestar** [comment]
I've now redrawn the huaptzone. After that I could actually access the gui. Now I have tested further. All zones which are not drawn by me I can call the Gui. But all zones that I have drawn as owner will get this error message. So I would have to redraw all zones I have drawn!!

**Comment by Blueeyestar** [comment]
With the version RedProtect-7.6.0-b194-Universal.jar everything works as it should. A mega super thanks to FabioZumbi12 for the super work he does again and again :)
