### ISSUE TITLE
[BUG] Critical RP Error* Zone Clearance*

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#431]
RP-Version:RedProtect-7.6.0-b197-Universal

Spigot-Version:CraftBukkit version git-Spigot-1eece4f-dadc539 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

**Unfortunately, I have another problem to report. The uuid go now. But now Red Protect deletes half of the zone entries itself after starting.**

**Before starting:**

![data1](https://user-images.githubusercontent.com/35557302/57011427-d96bd280-6c01-11e9-8ad9-1862995b86f6.png)

**After starting:**

![data2](https://user-images.githubusercontent.com/35557302/57011441-edafcf80-6c01-11e9-80cd-80663c069a1b.png)

**After that, the suns are no longer present.**

[11:05:41] [Server thread/INFO]: RedProtect jar: RedProtect-7.6.0-b197-Universal.jar
[11:05:41] [Server thread/WARN]: java.lang.NullPointerException
[11:05:41] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.lambda$loadRegion$5(RedProtectUtil.java:997)
[11:05:41] [Server thread/WARN]: 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[11:05:41] [Server thread/WARN]: 	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
[11:05:41] [Server thread/WARN]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[11:05:41] [Server thread/WARN]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[11:05:41] [Server thread/WARN]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[11:05:41] [Server thread/WARN]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[11:05:41] [Server thread/WARN]: 	at java.util.stream.ReferencePipeline.collect(Unknown Source)
[11:05:41] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.loadRegion(RedProtectUtil.java:1002)
[11:05:41] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.database.WorldFlatFileRegionManager.load(WorldFlatFileRegionManager.java:114)
[11:05:41] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.database.WorldFlatFileRegionManager.load(WorldFlatFileRegionManager.java:68)
[11:05:41] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.load(RegionManager.java:74)
[11:05:41] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.loadAll(RegionManager.java:60)
[11:05:41] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:178)
[11:05:41] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.onEnable(RedProtect.java:102)
[11:05:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:05:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[11:05:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
[11:05:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
[11:05:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
[11:05:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
[11:05:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[11:05:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758)
[11:05:41] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Blueeyestar** [comment]
Should I send the whole RedProtec folder so you can reproduce the error?
