### ISSUE TITLE
[BUG] Unhandled exception executing command 'rp' in plugin RedProtect v7.6.0

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#436]
Spigot:CraftBukkit version git-Spigot-1eece4f-09a453a (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)
Red-Protec:Vers: RedProtect-7.6.0-b199-Universal.jar

https://pastebin.com/MFqe01wF

**Comment by Blueeyestar** [comment]
**This mistake comes no matter where I try to pull zone.** 

[09:48:24] [Server thread/INFO]: Blueeyestar issued server command: /rp define schnee
[09:48:24] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:896) [minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:889) [minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:806) [minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.lambda$PlayerToUUID$0(RedProtectUtil.java:428) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_201]
	at java.util.HashMap$EntrySpliterator.tryAdvance(HashMap.java:1720) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_201]
	at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.PlayerToUUID(RedProtectUtil.java:428) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.getPlayerRegions(RegionManager.java:204) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.actions.DefineRegionBuilder.<init>(DefineRegionBuilder.java:105) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.DefineCommand.onCommand(DefineCommand.java:77) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:158) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[minecraft_server.jar:git-Spigot-1eece4f-09a453a]
	... 17 more
[09:48:25] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2304ms or 46 ticks behind
