### ISSUE TITLE
[BUG]DynmapHook Problem 

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#439]
RP-Version: 200

Spigot-Ver: CraftBukkit version git-Spigot-1eece4f-68e72f6 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

[02:59:15] [Server thread/INFO]: [RedProtect] Saving world's regions...[m
[02:59:15] [Server thread/INFO]: [RedProtect] Saving world_the_end's regions...[m
[02:59:15] [Server thread/INFO]: [RedProtect] Unregistering listeners...[m
[02:59:15] [Server thread/INFO]: [RedProtect] RedProtect v7.6.0 turned off...[m
[02:59:15] [Server thread/INFO]: [RedProtect] Server version: 1.14-R0.1-SNAPSHOT[m
[02:59:16] [Server thread/INFO]: [RedProtect] All configurations loaded![m
[02:59:16] [Server thread/INFO]: [RedProtect] Language file loaded - Using: DE-DE[m
[02:59:16] [Server thread/INFO]: [RedProtect] Registering commands...[m
[02:59:16] [Server thread/INFO]: [RedProtect] Registering listeners...[m
[02:59:16] [Server thread/INFO]: [RedProtect] - Loading world's regions...[m
[02:59:16] [Server thread/INFO]: [RedProtect] - Loading world_the_end's regions...[m
[02:59:21] [Server thread/INFO]: [RedProtect] Auto-save Scheduler: Saving yml database every 60 minutes![m
[02:59:21] [Server thread/INFO]: [RedProtect] There are 250 regions on (yml) database![m
[02:59:21] [Server thread/INFO]: [RedProtect] Vault found. Hooked.[m
[02:59:21] [Server thread/INFO]: [RedProtect] WorldEdit found. Hooked.[m
[02:59:21] [Server thread/INFO]: [RedProtect] Dynmap found. Hooked.[m
[02:59:21] [Server thread/INFO]: [RedProtect] Loading dynmap markers...[m
[02:59:21] [Server thread/INFO]: RedProtect jar: RedProtect-7.6.0-b200-Universal.jar
[02:59:21] [Server thread/WARN]: java.lang.NullPointerException
[02:59:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:52)
[02:59:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooks(HooksManager.java:124)
[02:59:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:195)
[02:59:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.reload(RedProtect.java:150)
[02:59:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.AdminCommand.onCommand(AdminCommand.java:231)
[02:59:21] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:158)
[02:59:21] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:59:21] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[02:59:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:896)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:889)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:873)
[02:59:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:806)
[02:59:21] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by CloudeLecaw** [comment]
https://github.com/FabioZumbi12/RedProtect/issues/424

**Comment by Blueeyestar** [comment]
https://github.com/webbukkit/dynmap/issues/2469

**Comment by FabioZumbi12** [comment]
Theres no changes on dynmap hook codes since some versions, then its good to way a stable release of dynmap.
