### ISSUE TITLE
[BUG] org.bukkit.command.CommandException: Cannot execute command 'rp' in plugin RedProtect v7.6.0 - plugin is disabled.

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#442]
RP-version 205

Spigot:CraftBukkit version git-Spigot-1eece4f-0d76f86 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

[15:39:40] [Server thread/INFO]: Blueeyestar issued server command: /rp flag
[15:39:40] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'rp' in plugin RedProtect v7.6.0 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:896) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:889) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:806) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by FabioZumbi12** [comment]
`RedProtect v7.6.0 - plugin is disabled.` you have to check your server start logs

**Comment by Blueeyestar** [comment]
https://pastebin.com/7iQ8MTCB

**Comment by Blueeyestar** [comment]
Starting with the Rp version 202 Red Protect switches itself off. and subsequent versions all have the same problem. is due to the change:  **Change hooks load order**

**Comment by FabioZumbi12** [comment]
Humm, i think is fixed on latest dev build.

**Comment by Blueeyestar** [comment]
Gefixt. Thank :)
