### ISSUE TITLE
[BUG] Setminy and Setmaxy Problem

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#444]
RP-version: 207
Spigot: CraftBukkit version git-Spigot-1eece4f-d203283 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

**Good afternoon, users can no longer do /rp setmaxy or /rp setminy on their zone. If I then give the permission redprotect.command.admin.setmaxy or redprotect.command.admin.setminy. the error message appears. 

It would be nice if the zone owners would have this possibility again as well as set with the flag signs**

[20:30:24] [Server thread/INFO]: Mardelzur issued server command: /rp setmaxy 255
[20:30:24] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [minecraft_server.jar:git-Spigot-1eece4f-d203283]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.SetMaxYCommand.onCommand(SetMaxYCommand.java:91) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:158) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[minecraft_server.jar:git-Spigot-1eece4f-d203283]

**Comment by FabioZumbi12** [comment]
Fixed on latest!
