### ISSUE TITLE
[7.6.0 b200] Null error on /rp define

### ISSUE THREAD

**Issue by ironleather** [FabioZumbi12/RedProtect#458]
This is an error for the command /rp define

Plugin: RedProtect 7.6.0 b200
Server: PaperSpigot 20 (1.14.1)

This is what I see on console:
[INFO] ElekzaliZ issued server command: /rp define SS

[ERROR] null

org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.6.0

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.1.jar:git-Paper-20]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.1.jar:git-Paper-20]

at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1826) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1634) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$2952.00000000D8093440.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:995) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:988) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:972) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:906) ~[patched_1.14.1.jar:git-Paper-20]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NullPointerException

at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.getRegion(RegionManager.java:109) ~[?:?]

at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.nameGen(RedProtectUtil.java:279) ~[?:?]

at br.net.fabiozumbi12.RedProtect.Bukkit.actions.DefineRegionBuilder.<init>(DefineRegionBuilder.java:59) ~[?:?]

at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.DefineCommand.onCommand(DefineCommand.java:77) ~[?:?]

at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:158) ~[?:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.1.jar:git-Paper-20]

... 18 more

**Comment by FabioZumbi12** [comment]
The build 200 its too old, try the latest! We already are on 218 and this has been fixed.
