### ISSUE TITLE
[BUG]Dynmap Problem with RP-Version 219

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#459]
Spigot: CraftBukkit version git-Spigot-03bd4b0-342194e (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

RP-Version: 219

[14:22:25] [Server thread/INFO]: RedProtect jar: RedProtect-7.6.0-b219-Universal.jar
[14:22:25] [Server thread/WARN]: java.lang.NullPointerException
[14:22:25] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:52)
[14:22:25] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooksLast(HooksManager.java:133)
[14:22:25] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:195)
[14:22:25] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.reload(RedProtect.java:150)
[14:22:25] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.AdminCommand.onCommand(AdminCommand.java:317)
[14:22:25] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:158)
[14:22:25] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:22:25] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:22:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)
[14:22:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:692)
[14:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433)
[14:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397)
[14:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956)
[14:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801)
[14:22:25] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:22:25] [Server thread/INFO]: [LuluLand] RedProtect Plus reloaded!

**Comment by Blueeyestar** [comment]
**You don't see any zones on the dynmap when you have drawn them**


[18:13:59] [Server thread/INFO]: Blueeyestar issued server command: /rp redefine Peter261286
[18:14:00] [Server thread/WARN]: java.lang.NullPointerException
[18:14:00] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.removeMark(DynmapHook.java:91)
[18:14:00] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:249)
[18:14:00] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.actions.RedefineRegionBuilder.<init>(RedefineRegionBuilder.java:158)
[18:14:00] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.onCommand(RedefineCommand.java:66)
[18:14:00] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:158)
[18:14:00] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:14:00] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[18:14:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805)
[18:14:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:14:00] [Server thread/INFO]: [RedProtect] Problems when remove marks to Dynmap. Dynmap is updated?
[18:14:00] [Server thread/WARN]: java.lang.NullPointerException
[18:14:00] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.addMark(DynmapHook.java:102)
[18:14:00] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.add(RegionManager.java:230)
[18:14:00] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.onCommand(RedefineCommand.java:70)
[18:14:00] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:158)
[18:14:00] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:14:00] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[18:14:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871)
[18:14:00] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805)
[18:14:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by CrAazZyMaN21** [comment]
Dynmap Version?

[18:14:00] [Server thread/INFO]: [RedProtect] Problems when remove marks to Dynmap. Dynmap is updated?
