### ISSUE TITLE
[BUG] Console get filled with that error.

### ISSUE THREAD

**Issue by baxandrei** [FabioZumbi12/RedProtect#471]
**Describe the bug**

**To Reproduce**
I do not know exactly what the cause is, I think it's because of a Lingering type potion. I usually check the server logs for various reasons, and I noticed that 3 hours ago the console was full of this error.

**Expected behavior**
I do not know exactly what the cause is, I think it's because of a Lingering type potion.

**Screenshots and LOGs**
```
[19:35:02] [Server thread/ERROR]: Could not pass event LingeringPotionSplashEvent to RedProtect v7.6.0
java.lang.NoSuchMethodError: org.bukkit.event.entity.LingeringPotionSplashEvent.getEntity()Lorg/bukkit/entity/ThrownPotion;
	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.Compat19.onLingerPotion(Compat19.java:133) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor509.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-624]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callLingeringPotionSplashEvent(CraftEventFactory.java:552) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityPotion.a(EntityPotion.java:213) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityPotion.a(EntityPotion.java:88) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityProjectile.tick(EntityProjectile.java:160) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1562) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1529) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1340) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Server and plugins versions (please complete the following information):**
- Server: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
- Plugin Version: RedProtect-7.6.0-b233-Universal
- Java Version: openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-b04) OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**Additional context**
No.

**Comment by FabioZumbi12** [comment]
Try the latest dev build. Should be fixed.

**Comment by baxandrei** [comment]
Also I found this one:

```
[01:50:08] [Server thread/ERROR]: Could not pass event PortalCreateEvent to RedProtect v7.6.0
java.lang.NoSuchMethodError: org.bukkit.event.world.PortalCreateEvent.getBlocks()Ljava/util/List;
	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.PlayerListener.onPortalCreate(PlayerListener.java:1065) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor491.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-624]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.BlockPortal$Shape.createPortal(BlockPortal.java:356) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.BlockPortal.a(BlockPortal.java:65) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.BlockFire.onPlace(BlockFire.java:303) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:273) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:537) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1348) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by baxandrei** [comment]
Everything seems to be okay.

**Comment by FabioZumbi12** [comment]
Cool!

**Comment by baxandrei** [comment]
Oh, what about PortalCreateEvent ?
