### ISSUE TITLE
[BUG] Buyregion no longer works in the latest RP version

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#477]
RP-Version: 239

Spigot: CraftBukkit version git-Spigot-df0eb25-0309d17 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

[19:11:07] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BuyRegion v2.2.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:429) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:435) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1267) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.IncompatibleClassChangeError: Expected static method br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.isUUIDs(Ljava/lang/String;)Z
	at com.region.buyregion.plugins.RedProtectHook$RedRegion.lambda$getOwners$0(RedProtectHook.java:75) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_201]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_201]
	at com.region.buyregion.plugins.RedProtectHook$RedRegion.getOwners(RedProtectHook.java:75) ~[?:?]
	at com.region.buyregion.BuyRegion.onPunchSign(BuyRegion.java:436) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor638.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	... 19 more

**Comment by FabioZumbi12** [comment]
https://github.com/GentleGravel/BuyRegion/issues/8

;)
