### ISSUE TITLE
[BUG] Mysql Support

### ISSUE THREAD

**Issue by ShiroeSama** [FabioZumbi12/RedProtect#488]
**Hello FabioZumbi12, I have a bug with mysql support.

** Version **
RedProtect-7.6.1-b242-Universal

** BUG **
Claim a region after selected zone with wand tool.

**Log**

[20:09:46] [User Authenticator #3/INFO] [minecraft/NetHandlerLoginServer]: UUID of player floppy_disk is 2c6cbebf-9607-4c50-a629-78c1451e9266
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: java.sql.SQLDataException: (conn:12537) Data too long for column 'leaders' at row 1
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:245)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:186)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager.addLiveRegion(WorldMySQLRegionManager.java:196)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager.add(WorldMySQLRegionManager.java:167)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at br.net.fabiozumbi12.RedProtect.Sponge.region.RegionManager.add(RegionManager.java:200)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at br.net.fabiozumbi12.RedProtect.Sponge.commands.SubCommands.RegionHandlers.ClaimCommand.lambda$register$0(ClaimCommand.java:81)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlj000(SourceFile:539)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3955)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[20:09:54] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:200]: 	at java.lang.Thread.run(Thread.java:748)
[20:09:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.sql.SQLException: Data too long for column 'leaders' at row 1
Query is: INSERT INTO `redprotect_RepubliCraft_1.6.4` (name,leaders,admins,members,maxMbrX,minMbrX,maxMbrZ,minMbrZ,minY,maxY,centerX,centerZ,date,wel,prior,world,value,tppoint,candelete,flags) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?), parameters ['ShiroeS_Test','b5d39042-cb0a-402c-bea9-7d153fe73c1d@ShiroeS','','',-10,-22,191,179,0,255,-16,185,'02/07/2019','',0,'RepubliCraft_1.6.4',0,'',1,'can-grow:true,leaves-decay:false,allow-effects:true,door:false,teleport:true,allow-spawner:false,mob-loot:false,button:false,fire:false,flow:true,iceform-player:true,allow-home:false,chest:false,iceform-world:true,smart-door:true,fishing:false,use-potions:true,lever:false,pvp:false,spawn-animals:true,passives:false,press-plate:false,minecart:false,ender-chest:false,build:false,allow-fly:true,gravity:true,flow-damage:false,spawn-monsters:true,allow-potions:true']
[20:09:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
[20:09:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:223)
[20:09:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:212)
[20:09:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 28 more

**To Reproduce**
1. Connect to the server (With Mysql Support Enable)
2.Get the wand
3.Select Region/Zone
4.Claim it
5.Normaly you see an error in console and if you enter /rp list you couldn't see any region in the chat

**Server and plugins versions**
- Server : Sponge Forge 1.12.2 7.1.5.2768
- Plugins Version : RedProtect-7.6.1-b242-Universal
- Java Version : 1.8**

**Comment by FabioZumbi12** [comment]
Did you have used RP before with mysql and it worked or is a new installation?

Do you have some experience with mysql to make a test?

**Comment by ShiroeSama** [comment]
Yes it's a new installation.
I removed all old configs and tables in database.

Yes, I some experience with mysql, I use mariadb.

**Comment by ShiroeSama** [comment]
I think the bug comes from the limit of the table structure.
Because when the claim is made, the plugin try to insert in the leaders column a string greater than the definition of the column.

Leaders column is a varchar(36), but the string is bigger.

**Comment by FabioZumbi12** [comment]
Exact!

According the error: `java.sql.SQLDataException: (conn:12537) Data too long for column 'leaders' at row 1` the problems is whats you have mentioned.

Can you try to change the chars limit in your database after creation to see if works?

**Comment by ShiroeSama** [comment]
Yes it's working! :)

I change the size to 200 characters and the claim work perfectly.

**Comment by ShiroeSama** [comment]
Hi, FabioZumbi12

Thanks to your reactivity ;)

Continue like that !
You do a great job on this plugins ! ;)

Ps: I assume I have to download the latest jenkins build to use the patch, unless a new realease comes out soon.
