### ISSUE TITLE
[BUG] New item Gui system errors

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#492]
**Now you can put in a Gui the item you are allowed to mine on the zone and what not. Or what you are allowed to plant. 

This also works quite well, if you haven't entered something before version 247.
I had entered blue shulker boxes which can be dismantled.  If you then enter /rp flag allow-break you get an error**

[22:21:10] [Server thread/INFO]: Blueeyestar issued server command: /rp flag allow-break
[22:21:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.6.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.blue_shulker_box
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.Material.valueOf(Material.java:1) ~[minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.ItemFlagGui.lambda$new$2(ItemFlagGui.java:61) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:1.8.0_201]
	at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.ItemFlagGui.<init>(ItemFlagGui.java:61) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandlers.handleFlag(CommandHandlers.java:852) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.FlagCommand.onCommand(FlagCommand.java:127) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:282) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[minecraft_server.jar:git-Spigot-d05d3c1-087a2cf]
	... 17 more

**Only if you enter /rp flag allow-break remove to delete the shulker then you can open the gui as it was intended.**

**Then the new system runs Prima. 
Super that you could implement the idea. Can you also do that so that it is applicable in the wilderness?
As suggested in my idea. It's almost like that.
https://github.com/FabioZumbi12/RedProtect/issues/410**

Thank you so much for still doing this for us after so many years.

**Comment by FabioZumbi12** [comment]
Thanks ^^ !!

Should be fixed on latest dev build. The gui for wilderness flags will need wait more... its no easy to implement that!
