### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by Sckaletz** [FabioZumbi12/RedProtect#5]
The MySql isn't working. It adds "_world" to the database entered in the config.

29.07 06:57:20 [Server] INFO No new version available
29.07 06:57:19 [Server] INFO Checking for Updates ... 
29.07 06:57:19 [Multicraft] Skipped 153 lines due to rate limit (30/s)
29.07 06:57:19 [Server] Startup Done (4.946s)! For help, type "help" or "?"
29.07 06:57:19 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
29.07 06:57:19 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
29.07 06:57:19 [Server] WARN at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:101)
29.07 06:57:19 [Server] WARN at br.net.fabiozumbi12.RedProtect.RegionManager.loadAll(RegionManager.java:30)
29.07 06:57:19 [Server] WARN at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.<init>(WorldMySQLRegionManager.java:56)
29.07 06:57:19 [Server] WARN at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1581)
29.07 06:57:19 [Server] WARN at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1662)
29.07 06:57:19 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
29.07 06:57:19 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
29.07 06:57:19 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
29.07 06:57:19 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
29.07 06:57:19 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
29.07 06:57:19 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
29.07 06:57:19 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:382)
29.07 06:57:19 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
29.07 06:57:19 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
29.07 06:57:19 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
29.07 06:57:19 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
29.07 06:57:19 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
29.07 06:57:19 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'vanilla_db'@'localhost' to database 'vanilla_db_world'
29.07 06:57:19 [Server] INFO Redprotect: [Language file loaded - Using: EN-US]
29.07 06:57:19 [Server] INFO Redprotect: [All configurations loaded!]
29.07 06:57:19 [Server] INFO Enabling RedProtect v5.5.1

**Comment by FabioZumbi12** [comment]
The error is on the redprotect try to create the database! In this line:
29.07 06:57:19 [Server] WARN at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.(WorldMySQLRegionManager.java:56)

The redprotect try to create the database, and in this other line show access denied to the user:
29.07 06:57:19 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'vanilla_db'@'localhost' to database 'vanilla_db_world'

Please review the configuration and try again!

**Comment by Sckaletz** [comment]
Well access to the sql is fine and working with other plugins. But it says .... to database 'vanilla_db_world'. My database is called 'vanilla_db' and typed correctly in the config.

**Comment by jfort** [comment]
I have same problem. Redprotect is trying to open database for every world and db name is, like Sckaletz wrote, DbNameFromConfig_WorldName. And even if I manually create this database for every world, Redprotect don't create table region.

Error:
[18:58:36 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'tcraft_redprotect_world.region' doesn't exist
[18:58:36 WARN]:        at sun.reflect.GeneratedConstructorAccessor200.newInstance(Unknown Source)
[18:58:36 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:58:36 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[18:58:36 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[18:58:36 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[18:58:36 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[18:58:36 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[18:58:36 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[18:58:36 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[18:58:36 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[18:58:36 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[18:58:36 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
[18:58:36 WARN]:        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474)
[18:58:36 WARN]:        at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.getTotalRegionNum(WorldMySQLRegionManager.java:742)
[18:58:36 WARN]:        at br.net.fabiozumbi12.RedProtect.RegionManager.getTotalRegionsNum(RegionManager.java:245)
[18:58:36 WARN]:        at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:160)
[18:58:36 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:58:36 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:58:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:58:36 WARN]:        at br.net.fabiozumbi12.RedProtect.RPCommands.onCommand(RPCommands.java:177)
[18:58:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:58:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[18:58:36 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[18:58:36 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697)
[18:58:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:472)
[18:58:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[18:58:36 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[18:58:36 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[18:58:36 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by FabioZumbi12** [comment]
Please, try this version and see if solve: http://areaz12server.net.br/download/RedProtect.jar
