### ISSUE TITLE
[BUG] 1.9 get Could not pass event ProjectileHitEvent to RedProtect v7.6.3

### ISSUE THREAD

**Issue by boyphongsakorn** [FabioZumbi12/RedProtect#532]
i get error in 1.9 my minecraft server like this

```
[19:44:34] [Server thread/ERROR]: Could not pass event ProjectileHitEvent to RedProtect v7.6.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:779) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityProjectile.m(EntityProjectile.java:168) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.World.entityJoinedWorld(World.java:1617) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.World.g(World.java:1592) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.World.tickEntities(World.java:1426) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.WorldServer.tickEntities(WorldServer.java:632) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:797) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.ProjectileHitEvent.getHitBlock()Lorg/bukkit/block/Block;
	at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.BlockListener.onChorusBreak(BlockListener.java:349) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	... 14 more
```

**Comment by FabioZumbi12** [comment]
This is already fixed on latest dev builds
