### ISSUE TITLE
[BUG] Console stuck, and it may caused by Redprotect

### ISSUE THREAD

**Issue by baibo233** [FabioZumbi12/RedProtect#583]
**Describe the bug**
Server thread error, probably caused by Redprotect use hashmap repeatedly.

**To Reproduce**
When the server runs for some time,  and the console may stuck.
Any of my command (eg./stop /restart /list) entered in console was no response

**Expected behavior**
console stuck
but I used jstack and I found it may caused by Redprotect using hashmap error

**Screenshots and LOGs**
-jstack log belows:
```
"pool-3-thread-6893" #10169 prio=5 os_prio=0 tid=0x0000000056d3a000 nid=0x26e8 runnable [0x000000005bc7e000]
   java.lang.Thread.State: RUNNABLE
        at java.util.HashMap$TreeNode.balanceDeletion(HashMap.java:2338)
        at java.util.HashMap$TreeNode.removeTreeNode(HashMap.java:2112)
        at java.util.HashMap.removeNode(HashMap.java:840)
        at java.util.HashMap$HashIterator.remove(HashMap.java:1462)
        at java.util.Collection.removeIf(Collection.java:415)
        at br.net.fabiozumbi12.RedProtect.Sponge.region.RegionManager.getTopRegion(RegionManager.java:267)
        at br.net.fabiozumbi12.RedProtect.Sponge.listeners.PlayerListener.RegionFlags(PlayerListener.java:134
9)
        at br.net.fabiozumbi12.RedProtect.Sponge.listeners.PlayerListener.lambda$onPlayerTeleport$0(PlayerLis
tener.java:891)
        at br.net.fabiozumbi12.RedProtect.Sponge.listeners.PlayerListener$$Lambda$2560/1291192599.run(Unknown
 Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at org.spongepowered.common.scheduler.TaskExecutorService$RepeatableFutureTask.run(TaskExecutorServic
e.java:263)
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
        at org.spongepowered.api.scheduler.Task$Builder$$Lambda$591/570736730.accept(Unknown Source)
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197)
        at org.spongepowered.common.scheduler.SchedulerBase$$Lambda$656/2002290722.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Server and plugins versions :**
 - Server: [ Sponge 1.12.2, Spongeforge7.1.10]
 - Plugin Version: [RedProtect-7.6.5-b297-Universal.jar]
 - Java Version: [Java 1.8]

**Additional context**
I used the latest version of Redprotect, but the problem was still.

**Comment by FabioZumbi12** [comment]
Redprotect its in this log because it try to launch the plugin events during the freezed server, as redprotect listen for player walk, teleport and some of player events. Its not exactly the cause of the crash
