### ISSUE TITLE
Could not pass event PlayerInteractEvent to RedProtect v7.6.5 [BUG] 

### ISSUE THREAD

**Issue by ChrisTVH** [FabioZumbi12/RedProtect#597]
**Brief description of the bug**
This error occurs when I try to interact with anything in the protection by right and left clicking

**Error**
```
[12:25:40 ERROR]: Could not pass event PlayerInteractEvent to RedProtect v7.6.5
java.lang.NoSuchFieldError: CARROTS
at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.BlockListener.onPlayerInteract(BlockListener.java:326) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor499.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:486) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Server information**
 - Server: [Paper-1618 (MC: 1.12.2)]
 - Plugin Version: [ RedProtect-7.6.5-b151-Universal.jar]
 - Java Version: [ Java 1.8]

**Other error**
```
[12:40:16 ERROR]: [RedProtect] Plugin RedProtect v7.6.5 has failed to register events for class br.net.fabiozumbi12.RedProtect.Bukkit.hooks.McMMOHook because com/gmail/nossr50/events/skills/secondaryabilities/SubSkillRandomCheckEvent does not exist.
```
**That happens when the plugin starts or I put rp reload**

**Comment by CloudeLecaw** [comment]
oSuchFieldError: CARROTS

look for the item where u have defined CARROTS
if your using Version 1.12.2 they may have an other name? Please check this.

**Comment by ChrisTVH** [comment]
What do you mean, where do I find carrots?

**Comment by KiralyCraft** [comment]
I think he meant that you may be developing a plugin together with RedProtect. You don't seem to have the latest version of RP either. The latest is: RedProtect-7.6.5-b298-Universal

**Comment by ChrisTVH** [comment]
Ok thanks i will try it right now

**Comment by KiralyCraft** [comment]
If it works please confirm and close this issue. (I'm not associated with RedProtect in any way but I'm trying to help :) )

**Comment by CloudeLecaw** [comment]
Well ..the latest Version is 303....
https://www.file-upload.net/download-13967738/RedProtect_7.6.5-Build303-Universal.jar.html

**Comment by ChrisTVH** [comment]
I fix the error thanks to how fast the updates come out hehe

**Comment by KiralyCraft** [comment]
I seem to be late on updates, thanks for letting me know. Where did you get Build 303? Jenkins seems down for me

**Comment by CloudeLecaw** [comment]
303 was was online since since 14.03.2020
But the servers are down since a weeks or so..

**Comment by KiralyCraft** [comment]
Didn't get to see that thread. I remember trying Jenkins a few times past the last weeks and it was still down, so I assumed 298 was the latest. I'll update asap, let's not spam Chris's email, lol
