### ISSUE TITLE
/rp panel Error

### ISSUE THREAD

**Issue by krzxsiek** [FabioZumbi12/RedProtect#6]
I have KCauldron 1.7.10 server, before update to RedProtect 5.5.4 everything working good.

[13:30:09] [Server thread/INFO]: krzxsiek issued server command: /rp panel
[13:30:09] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v5.5.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1492.152]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1492.152]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1492.152]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.IllegalStateException: Unable to find method getTypeId ([]).
	at br.net.fabiozumbi12.RedProtect.NbtFactory.getMethod(NbtFactory.java:744) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.NbtFactory.getMethod(NbtFactory.java:743) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.NbtFactory.<init>(NbtFactory.java:340) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.NbtFactory.get(NbtFactory.java:320) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.NbtFactory.getCraftItemStack(NbtFactory.java:559) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RPGui.removeAttribute(RPGui.java:154) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RPGui.<init>(RPGui.java:69) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.RPCommands.onCommand(RPCommands.java:417) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1492.152]
	... 13 more

**Comment by FabioZumbi12** [comment]
Fixed on next version! Sorry ;)

**Comment by krzxsiek** [comment]
ok I'm waiting :)

**Comment by FabioZumbi12** [comment]
Fixed ^^
http://dev.bukkit.org/bukkit-plugins/region-protect-plus/files/81-red-protect-v5-5-5/
