### ISSUE TITLE
[BUG] Redprotect or Dynmap bug?

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#664]
On Load and Reload of RedProtect we got this Error

```
[00:02:46] [Server thread/INFO]: [RedProtect] - Loading world_nether's regions...
[00:02:46] [Server thread/INFO]: [RedProtect] - Loading world_the_end's regions...
[00:02:47] [Server thread/INFO]: [RedProtect] Auto-save Scheduler: Saving yml database every 60 minutes!
[00:02:47] [Server thread/INFO]: [RedProtect] There are 302 regions on (yml) database!
[00:02:47] [Server thread/INFO]: [RedProtect] Dynmap found. Hooked.
[00:02:47] [Server thread/INFO]: [RedProtect] Loading dynmap markers...
[00:02:47] [Server thread/WARN]: java.lang.NullPointerException
[00:02:47] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:51)
[00:02:47] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooksLast(HooksManager.java:183)
[00:02:47] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:215)
[00:02:47] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.reload(RedProtect.java:152)
[00:02:47] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:584)
[00:02:47] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:02:47] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[00:02:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792)
[00:02:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:754)
[00:02:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[00:02:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[00:02:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[00:02:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[00:02:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[00:02:47] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

We are not sure if this eror is RP oder Dynmap related, so i postd this in both forums

**Comment by CloudeLecaw** [comment]
>.... [22:28:09 INFO]: Blueeyestar issued server command: /rp redefine Nervenarzt_0
>.... [22:28:17 WARN]: java.lang.NullPointerException
>.... [22:28:17 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.removeMark(DynmapHook.java:90)
>.... [22:28:17 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:266)
>.... [22:28:17 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.actions.RedefineRegionBuilder.<init>(RedefineRegionBuilder.java:188)
>.... [22:28:17 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.lambda$onCommand$0(RedefineCommand.java:71)
>.... [22:28:17 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
>.... [22:28:17 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [22:28:17 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [22:28:17 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [22:28:17 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [22:28:17 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [22:28:17 INFO]: [RedProtect] Problems when remove marks to Dynmap. Is Dynmap updated?
>.... [22:28:17 WARN]: java.lang.NullPointerException
>.... [22:28:17 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.addMark(DynmapHook.java:101)
>.... [22:28:17 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.add(RegionManager.java:235)
>.... [22:28:17 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.lambda$onCommand$0(RedefineCommand.java:75)
>.... [22:28:17 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
>.... [22:28:17 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [22:28:17 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [22:28:17 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [22:28:17 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [22:28:17 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [22:28:17 INFO]: [RedProtect] Problems when add marks to Dynmap. Dynmap is updated?

**Comment by FabioZumbi12** [comment]
The second error is caused by the first error. Btw, theres no changes on RP code for Dynmap.

**Comment by FabioZumbi12** [comment]
Still getting errors? I cant reproduce this?

**Comment by CloudeLecaw** [comment]
I will close this for now, may the Redprotect or the Dynmap code have been Updated. :)
