### ISSUE TITLE
is spams my console

### ISSUE THREAD

**Issue by PeRFecTxTabZ** [FabioZumbi12/RedProtect#67]
[18:58:21 ERROR]: Could not pass event PlayerItemConsumeEvent to RedProtect v6.5.9
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.EntityHuman.s(EntityHuman.java:297) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.EntityPlayer.s(EntityPlayer.java:885) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:142) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:285) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:382) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
at br.net.fabiozumbi12.RedProtect.RPUtil.denyPotion(RPUtil.java:90) ~[?:?]
at br.net.fabiozumbi12.RedProtect.listeners.RPPlayerListener.onConsume(RPPlayerListener.java:150) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
... 19 more

**Comment by FabioZumbi12** [comment]
I think is fixed.

**Comment by PeRFecTxTabZ** [comment]
mhh, why do you not Update it on Spigot? :/

**Comment by FabioZumbi12** [comment]
Theres more issues to solve before update. Your problem was fixed?

**Comment by PeRFecTxTabZ** [comment]
I have not seen the error until now. I think it works :) Thx
