### ISSUE TITLE
[BUG] Console Spamming

### ISSUE THREAD

**Issue by BlackID512** [FabioZumbi12/RedProtect#686]
RedProtect ver: 7.7.2
Spigot: StellarSpigot Latest Dev (1.8.8)

Console is spamming like this

[18:34:45 ERROR]: Could not pass event EntityDamageByBlockEvent to RedProtect v7.7.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:509) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:626) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1160) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:871) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:794) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:812) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:507) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityLiving.O(EntityLiving.java:1252) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.Entity.K(Entity.java:350) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:191) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:263) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1516) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:179) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:293) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:362) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at sun.reflect.GeneratedMethodAccessor861.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
at us.myles.ViaVersion.bukkit.providers.BukkitViaMovementTransmitter.sendPlayer(BukkitViaMovementTransmitter.java:91) [ViaVersion-3.0.1.jar:git-ViaVersion-3.0.1:1a7ce90]
at us.myles.ViaVersion.protocols.protocol1_9to1_8.ViaIdleThread.run(ViaIdleThread.java:18) [ViaVersion-3.0.1.jar:git-ViaVersion-3.0.1:1a7ce90]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:794) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [StellarSpigot-LatestDev.jar:git-TacoSpigot-bf023c7d]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException

**Comment by FabioZumbi12** [comment]
Its sems you have some problema with ViaVersion and StellarServer. RedProtect was not tested in this server version and its maded for spigot and spexially for Mohist (spigot plugins + mods). I dont  recommend any other type of server than paper and mohist.
