### ISSUE TITLE
Error on trying to redefine a region

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#687]
```
> [15:10:30] [Server thread/INFO]: Blueeyestar issued server command: /rp redefine Crashkorni_0
> [15:10:36] [Craft Scheduler Thread - 472/WARN]: [RedProtect] Plugin RedProtect v7.7.2 generated an exception while executing task 15175205
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_242]
at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_242]
at java.util.AbstractCollection.removeAll(AbstractCollection.java:375) ~[?:1.8.0_242]
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.removeCache(RegionManager.java:284) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:264) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.actions.RedefineRegionBuilder.<init>(RedefineRegionBuilder.java:200) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.lambda$onCommand$0(RedefineCommand.java:71) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-d65430a-bad55db]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:git-Spigot-d65430a-bad55db]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

we saw this in the log when tried to redefine the size of a region.

**Comment by CloudeLecaw** [comment]
Solved and fixed
