### ISSUE TITLE
[BUG] Zone is deleted with / rp redefine

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#695]
RP-Version: 376
Paper: Paper version git-Paper-192 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**we have the problem on the server if you want to redefine a large zone with / rp redefine that is then deleted!
This problem already occurred in 1.16.2**

```
>.... [14:48:57 INFO]: Blueeyestar issued server command: /rp redefine ItzMaxGamesTo
>.... [14:48:57 WARN]: [RedProtect] Plugin RedProtect v7.7.2 generated an exception while executing task 1493473
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_242]
at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_242]
at java.util.AbstractCollection.removeAll(AbstractCollection.java:375) ~[?:1.8.0_242]
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.removeCache(RegionManager.java:286) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:266) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.actions.RedefineRegionBuilder.<init>(RedefineRegionBuilder.java:200) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.lambda$onCommand$0(RedefineCommand.java:71) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-192]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-192]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-192]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] 
```

**Comment by Blueeyestar** [comment]
The problem still exists that you cannot expand zones with /rp redefine, but delete them.

**Comment by Blueeyestar** [comment]
>.... [21:53:44 INFO]: Blueeyestar issued server command: /rp redefine theflaxser223_0
>.... [21:53:44 WARN]: [RedProtect] Plugin RedProtect v7.7.2 generated an exception while executing task 3903943
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.remove(HashMap.java:1459) ~[?:1.8.0_242]
at java.util.AbstractCollection.removeAll(AbstractCollection.java:376) ~[?:1.8.0_242]
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.removeCache(RegionManager.java:286) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:266) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.actions.RedefineRegionBuilder.<init>(RedefineRegionBuilder.java:200) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.lambda$onCommand$0(RedefineCommand.java:71) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-207]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-207]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
>.... [21:54:12 INFO]: Blueeyestar issued server command: /rp zone
>.... [21:54:17 INFO]: Blueeyestar issued server command: /zone
>.... [21:54:23 INFO]: Blueeyestar issued server command: /grenze
>.... [21:54:27 INFO]: Blueeyestar issued server command: /grenze
>.... [21:54:38 INFO]: Blueeyestar issued server command: /grenze
>.... [21:55:08 INFO]: Blueeyestar issued server command: /rp define theflaxser223_0
>.... [21:55:35 INFO]: Blueeyestar issued server command: /grenze
>.... [21:55:39 INFO]: Blueeyestar issued server command: /grenze
>.... [21:55:43 INFO]: Blueeyestar issued server command: /grenze
>.... [21:55:52 INFO]: Blueeyestar issued server command: /rp redefine theflaxser223_0
>.... [21:55:52 WARN]: [RedProtect] Plugin RedProtect v7.7.2 generated an exception while executing task 3963853
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_242]
at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_242]
at java.util.AbstractCollection.removeAll(AbstractCollection.java:375) ~[?:1.8.0_242]
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.removeCache(RegionManager.java:286) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:266) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.actions.RedefineRegionBuilder.<init>(RedefineRegionBuilder.java:200) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.lambda$onCommand$0(RedefineCommand.java:71) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-207]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-207]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by CloudeLecaw** [comment]
i tested this also
5 times it worked the 6th time i got the same issue

```
>.... [23:34:06 INFO]: Cloude_Lecaw issued server command: /rp info
>.... [23:34:31 INFO]: Cloude_Lecaw issued server command: /rp redefine simplyPOLO_0
>.... [23:34:55 INFO]: Cloude_Lecaw issued server command: /rp redefine simplyPOLO_0
>.... [23:35:06 INFO]: Cloude_Lecaw issued server command: /rp redefine simplyPOLO_0
>.... [23:35:26 INFO]: Cloude_Lecaw issued server command: /rp redefine simplyPOLO_0
>.... [23:35:40 INFO]: Cloude_Lecaw issued server command: /rp redefine simplyPOLO_0
>.... [23:35:40 WARN]: [RedProtect] Plugin RedProtect v7.7.2 generated an exception while executing task 28275164
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_242]
at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_242]
at java.util.AbstractCollection.removeAll(AbstractCollection.java:375) ~[?:1.8.0_242]
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.removeCache(RegionManager.java:286) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:266) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.actions.RedefineRegionBuilder.<init>(RedefineRegionBuilder.java:200) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.lambda$onCommand$0(RedefineCommand.java:71) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-207]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-207]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by Blueeyestar** [comment]
**I have now also used the normal spigot version, not just the paper version. The error comes there too**

CraftBukkit version git-Spigot-988b411-aa8206a (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)




```
[20:00:44] [Server thread/INFO]: Blueeyestar issued server command: /rp redefine Nervenarzt_0
[20:00:45] [Server thread/INFO]: Blueeyestar issued server command: /rp yes
[20:00:45] [Craft Scheduler Thread - 2/WARN]: [RedProtect] Plugin RedProtect v7.7.2 generated an exception while executing task 6285
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.remove(Unknown Source) ~[?:1.8.0_231]
	at java.util.AbstractCollection.removeAll(Unknown Source) ~[?:1.8.0_231]
	at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.removeCache(RegionManager.java:286) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:266) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.actions.RedefineRegionBuilder.<init>(RedefineRegionBuilder.java:200) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.lambda$onCommand$0(RedefineCommand.java:71) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-988b411-aa8206a]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:git-Spigot-988b411-aa8206a]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```
