### ISSUE TITLE
Problem with Dynmap?[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#698]
```
>.... [23:23:58 INFO]: [RedProtect] Loading dynmap markers...
>.... [23:23:58 WARN]: java.lang.NullPointerException
>.... [23:23:58 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:57)
>.... [23:23:58 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooksLast(HooksManager.java:183)
>.... [23:23:58 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:238)
>.... [23:23:58 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.reload(RedProtect.java:174)
>.... [23:23:58 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:584)
>.... [23:23:58 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [23:23:58 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [23:23:58 WARN]: at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
>.... [23:23:58 WARN]: at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchServerCommand(CraftServer.java:764)
>.... [23:23:58 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:405)
>.... [23:23:58 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372)
>.... [23:23:58 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
>.... [23:23:58 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [23:23:58 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [23:23:58 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [23:23:58 INFO]: [RedProtect] Helper version: Latest
>.... [23:23:58 INFO]: [RedProtect] Loading GuiFlags for 1.14+
>.... [23:23:58 INFO]: [LuluLand] RedProtect Plus reloaded!
>.... [23:24:01 INFO]: Gobaryl issued server command: /claim
>.... [23:24:01 WARN]: java.lang.NullPointerException
>.... [23:24:01 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.addMark(DynmapHook.java:103)
>.... [23:24:01 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.add(RegionManager.java:238)
>.... [23:24:01 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.ClaimCommand.lambda$onCommand$0(ClaimCommand.java:76)
>.... [23:24:01 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
>.... [23:24:01 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [23:24:01 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [23:24:01 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [23:24:01 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [23:24:01 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [23:24:01 INFO]: [RedProtect] Problems when add marks to Dynmap. Dynmap is updated?
```
in resilt the claiming is not passible claim
the both seems to be effected by dynmap

![Snag_152e439](https://user-images.githubusercontent.com/12080017/93648399-fa0d1600-fa0a-11ea-83ef-779a2ee192ba.png)

![image](https://user-images.githubusercontent.com/12080017/93648448-18731180-fa0b-11ea-9b3d-e22798a36bd7.png)

**Comment by CloudeLecaw** [comment]
Seems solved

**Comment by CloudeLecaw** [comment]
Issue still exists on RP Reload

it this bug comming from dynmap? or from RedProtect?

```
>.... [09:06:47 INFO]: [RedProtect] There are 357 regions on (yml) database!
>.... [09:06:47 INFO]: [RedProtect] Dynmap found. Hooked.
>.... [09:06:47 INFO]: [RedProtect] Loading dynmap markers...
>.... [09:06:47 WARN]: java.lang.NullPointerException
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:57)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooksLast(HooksManager.java:183)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:238)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.reload(RedProtect.java:174)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:584)
>.... [09:06:47 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [09:06:47 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [09:06:47 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
>.... [09:06:47 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
>.... [09:06:47 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [09:06:47 INFO]: [RedProtect] Helper version: Latest
>.... [09:06:47 INFO]: [RedProtect] Loading GuiFlags for 1.14+
>.... [09:06:47 INFO]: [LuluLand] RedProtect Plus reloaded!
```

**Comment by CloudeLecaw** [comment]
Issue still exists on RP Reload

it this bug comming from dynmap? or from RedProtect?

```
>.... [09:06:47 INFO]: [RedProtect] There are 357 regions on (yml) database!
>.... [09:06:47 INFO]: [RedProtect] Dynmap found. Hooked.
>.... [09:06:47 INFO]: [RedProtect] Loading dynmap markers...
>.... [09:06:47 WARN]: java.lang.NullPointerException
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:57)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooksLast(HooksManager.java:183)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:238)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.reload(RedProtect.java:174)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:584)
>.... [09:06:47 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [09:06:47 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [09:06:47 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
>.... [09:06:47 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
>.... [09:06:47 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [09:06:47 INFO]: [RedProtect] Helper version: Latest
>.... [09:06:47 INFO]: [RedProtect] Loading GuiFlags for 1.14+
>.... [09:06:47 INFO]: [LuluLand] RedProtect Plus reloaded!
```
