### ISSUE TITLE
Error in Console (new)

### ISSUE THREAD

**Issue by PeRFecTxTabZ** [FabioZumbi12/RedProtect#70]
**[20:54:52 **ERROR**]: Could not pass event BrewEvent to RedProtect v6.5.9
org.bukkit.event.EventException**
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.TileEntityBrewingStand.o(TileEntityBrewingStand.java:153) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.TileEntityBrewingStand.c(TileEntityBrewingStand.java:75) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
at br.net.fabiozumbi12.RedProtect.RPUtil.denyPotion(RPUtil.java:72) ~[?:?]
at br.net.fabiozumbi12.RedProtect.listeners.RPPlayerListener.onBrewing(RPPlayerListener.java:106) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
... 12 more

**Comment by FabioZumbi12** [comment]
I wil upload the fixed version on spigot now!

**Comment by FabioZumbi12** [comment]
Fixed on latest version.
