### ISSUE TITLE
normal player can use /rp define without permission for it

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#704]
the normal player can use /rp define Name what creates a serverzone
They dont have the command in tabcomplet and also not in the help of rp

![image](https://user-images.githubusercontent.com/12080017/97505035-5f441780-1978-11eb-99e3-23d5ed9462d6.png)

RedProtect_7.7.2-Build380.jar, Dynmap_3.1-Beta4.jar, Server Paper 1.16.3 Build 251

Also a little error is latest dynmap...
```
>.... [23:41:59 INFO]: Cloude_Lecaw issued server command: /rp define TestRegion2
>.... [23:41:59 WARN]: java.lang.NullPointerException
>.... [23:41:59 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.addMark(DynmapHook.java:103)
>.... [23:41:59 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.add(RegionManager.java:238)
>.... [23:41:59 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.DefineCommand.lambda$onCommand$1(DefineCommand.java:91)
>.... [23:41:59 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
>.... [23:41:59 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [23:41:59 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [23:41:59 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [23:41:59 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [23:41:59 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [23:41:59 INFO]: [RedProtect] Problems when add marks to Dynmap. Dynmap is updated?
```

**usually onyl the Admins should be able to create serverzones** they not even have the permission
Also when i deleted the zone i got this error
```
>.... [23:44:56 INFO]: [RedProtect] Problems when remove marks to Dynmap. Is Dynmap updated?
>.... [23:44:56 WARN]: java.lang.NullPointerException
>.... [23:44:56 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.removeMark(DynmapHook.java:92)
>.... [23:44:56 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:268)
>.... [23:44:56 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandlers.handleDelete(CommandHandlers.java:332)
>.... [23:44:56 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.DeleteCommand.onCommand(DeleteCommand.java:55)
>.... [23:44:56 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:346)
>.... [23:44:56 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [23:44:56 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [23:44:56 WARN]: at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1918)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1729)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
>.... [23:44:56 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [23:44:56 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by FabioZumbi12** [comment]
I cant reproduce the permission error for redefine.

**Comment by CloudeLecaw** [comment]
the question is why people can use the command for rp redefine?
We are using Paper 1.16.4 - Build284 And RedProtect 7.2.2 Build 380
