### ISSUE TITLE
Error with dynmap on rp reload[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#737]
issue accour when your using dynmap together with Redportect and try to reload the  plugin with /rp reload

Issue still exists on RP Reload

it this bug comming from dynmap? or from RedProtect?
There seems to be a problem with reloading the markers..

```
>....=>.... [08:29:57 INFO]: [RedProtect] Saving Farmwelt's regions...
>.... [08:29:57 INFO]: [RedProtect] Saving world's regions...
>.... [08:29:57 INFO]: [RedProtect] Saving world_the_end's regions...
>.... [08:29:57 INFO]: [RedProtect] Saving world_nether's regions...
>.... [08:29:57 INFO]: [RedProtect] Saving island's regions...
>.... [08:29:57 INFO]: [RedProtect] Saving plotworld's regions...
>.... [08:29:57 INFO]: [RedProtect] Saving Rally's regions...
>.... [08:29:57 INFO]: [RedProtect] Saving tutorial's regions...
>.... [08:29:57 INFO]: [RedProtect] Saving testwelt's regions...
>.... [08:29:57 INFO]: [RedProtect] Saving karneval's regions...
>.... [08:29:57 INFO]: [RedProtect] Unregistering listeners...
>.... [08:29:57 INFO]: [RedProtect] RedProtect v7.7.3 turned off...
>.... [08:29:57 INFO]: [RedProtect] Server version: 1.16.5-R0.1-SNAPSHOT
>.... [08:29:57 INFO]: [RedProtect] All configurations loaded!
>.... [08:29:57 INFO]: [RedProtect] Language file loaded - Using: DE-DE
>.... [08:29:57 INFO]: [RedProtect] Registering commands...
>.... [08:29:57 INFO]: [RedProtect] Registering listeners...
>.... [08:29:57 INFO]: [RedProtect] Vault Economy found. Hooked.
>.... [08:29:57 INFO]: [RedProtect] Vault Permissions found. Hooked.
>.... [08:29:57 INFO]: [RedProtect] WorldEdit found. Hooked.
>.... [08:29:57 INFO]: [RedProtect] PlaceHolderAPI found. Hooked and registered some chat placeholders.
>.... [08:29:57 INFO]: [RedProtect] TranslationAPI found. Hooked.
>.... [08:29:57 INFO]: [RedProtect] - Loading world's regions...
>.... [08:29:58 INFO]: [RedProtect] - Loading world_the_end's regions...
>.... [08:29:58 INFO]: [RedProtect] - Loading Farmwelt's regions...
>.... [08:29:58 INFO]: [RedProtect] - Loading world_nether's regions...
>.... [08:29:58 INFO]: [RedProtect] - Loading island's regions...
>.... [08:29:58 INFO]: [RedProtect] - Loading plotworld's regions...
>.... [08:29:58 INFO]: [RedProtect] - Loading Rally's regions...
>.... [08:29:58 INFO]: [RedProtect] - Loading tutorial's regions...
>.... [08:29:58 INFO]: [RedProtect] - Loading testwelt's regions...
>.... [08:29:58 INFO]: [RedProtect] - Loading karneval's regions...
>.... [08:29:58 INFO]: [RedProtect] Auto-save Scheduler: Saving yml database every 60 minutes!
>.... [08:29:58 INFO]: [RedProtect] There are 356 regions on (yml) database!
>.... [08:29:58 INFO]: [RedProtect] Dynmap found. Hooked.
>.... [08:29:58 INFO]: [RedProtect] Loading dynmap markers...
>.... [08:29:58 WARN]: java.lang.NullPointerException
>.... [08:29:58 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:56)
>.... [08:29:58 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooksLast(HooksManager.java:183)
>.... [08:29:58 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:238)
>.... [08:29:58 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.reload(RedProtect.java:174)
>.... [08:29:58 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:584)
>.... [08:29:58 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [08:29:58 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [08:29:58 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
>.... [08:29:58 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769)
>.... [08:29:58 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
>.... [08:29:58 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
>.... [08:29:58 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
>.... [08:29:58 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
>.... [08:29:58 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
>.... [08:29:58 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [08:29:58 INFO]: [RedProtect] Helper version: Latest
>.... [08:29:58 INFO]: [RedProtect] Loading GuiFlags for 1.14+
>.... [08:29:58 INFO]: [LuluLand] RedProtect Plus reloaded!
```

Redprotect 7.7.3 - Build 392
Dynmap v3.1-beta-6
PaperMC: 1.16.5 - Build 467

i posted this issue also on the github of Dynmap

**Comment by CloudeLecaw** [comment]
Updated - see (errorlog  and used versions above)
