### ISSUE TITLE
[BUG] RedProtect just stopped working after some time

### ISSUE THREAD

**Issue by APlayGames** [FabioZumbi12/RedProtect#752]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

RedProtect v7.6.7

**Describe the bug**

The plugin just stopped working after some time, reloading sponge or server don't do anything.
/rp commands "don't exists" and dynmap don't show cuboids.

**To Reproduce**

I have no idea what happend, so I don't know how to reproduce it. Although I removed BetterPortals mod today from the server.

**Expected behavior**

The plugin was working fine for last 2 weeks but now it just doesn't work.

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://gist.github.com/

[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: java.lang.NullPointerException
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at br.net.fabiozumbi12.RedProtect.Sponge.RedProtect.shutDown(RedProtect.java:218)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at br.net.fabiozumbi12.RedProtect.Sponge.RedProtect.reload(RedProtect.java:283)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at br.net.fabiozumbi12.RedProtect.Sponge.RedProtect.onReloadPlugins(RedProtect.java:298)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.common.event.listener.GameReloadEventListener_RedProtect_onReloadPlugins19.handle(Unknown Source)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:467)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:249)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.common.command.SpongeCommandFactory.lambda$createSpongePluginsCommand$10(SpongeCommandFactory.java:629)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:433)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:398)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[14:09:15] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.RedProtect:reload:289]: 	at java.lang.Thread.run(Thread.java:748)

[14:16:01] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [RedProtect] RedProtect reloaded with success!

**Server and plugins versions (please complete the following information):**
 - Server: [e.g. Sponge 1.12.2, Spigot 1.13.2]
 Sponge 1.12.2
 - Plugin Version: [e.g. RedProtect-7.5.6-b151-Universal.jar]
 RedProtect-7.6.7-b342-Universal.jar
 - Java Version: [e.g. Java 1.8]
 Java 1.8

**Additional context**

**Comment by FabioZumbi12** [comment]
Download our latest dev build from: http://host.areaz12server.net.br:8081/job/RedProtect

We are on 7.7.3.

And if the problem stills, put all logs including redprotect and try to do not cut the errors logs.

**Comment by APlayGames** [comment]
The bug didn't go away.
Here are logs and debug from last 3 days including the day the plugin was still working.
[latest.log](https://github.com/FabioZumbi12/RedProtect/files/6064291/latest.log)
[debug.log](https://github.com/FabioZumbi12/RedProtect/files/6064295/debug.log)
[2021-02-28-1.log.gz](https://github.com/FabioZumbi12/RedProtect/files/6064309/2021-02-28-1.log.gz)
[debug-4.log.gz](https://github.com/FabioZumbi12/RedProtect/files/6064310/debug-4.log.gz)
[2021-02-28-2.log.gz](https://github.com/FabioZumbi12/RedProtect/files/6064311/2021-02-28-2.log.gz)
[debug-3.log.gz](https://github.com/FabioZumbi12/RedProtect/files/6064312/debug-3.log.gz)
[2021-02-28-3.log.gz](https://github.com/FabioZumbi12/RedProtect/files/6064313/2021-02-28-3.log.gz)
[2021-03-01-1.log.gz](https://github.com/FabioZumbi12/RedProtect/files/6064314/2021-03-01-1.log.gz)
[debug-2.log.gz](https://github.com/FabioZumbi12/RedProtect/files/6064315/debug-2.log.gz)
[2021-03-01-2.log.gz](https://github.com/FabioZumbi12/RedProtect/files/6064320/2021-03-01-2.log.gz)
[debug-1.log.gz](https://github.com/FabioZumbi12/RedProtect/files/6064321/debug-1.log.gz)


there are no logs from RedProtect from past 3 days since the plugin was not working probably and the last logs are empty since there was nothing happening then.

**Comment by APlayGames** [comment]
After many tries, changing sponge version and changing RedProtect version nothing worked.
The only thing I got is this error from Sponge
[20:34:11] [Server thread/WARN] [Sponge]: /*********************************************************************************************************************************/
[20:34:11] [Server thread/WARN] [Sponge]: /*                                             Could not pass  GameReloadEvent$Impl                                              */
[20:34:11] [Server thread/WARN] [Sponge]: /*********************************************************************************************************************************/
[20:34:11] [Server thread/WARN] [Sponge]: /* Could not pass the event GameReloadEvent$Impl to an Event Listener!                                                           */
[20:34:11] [Server thread/WARN] [Sponge]: /*                                                                                                                               */
[20:34:11] [Server thread/WARN] [Sponge]: /* Since the event can be modified during the event's listener,                                                                  */
[20:34:11] [Server thread/WARN] [Sponge]: /* there could be adverse side effects of the exception occurring                                                                */
[20:34:11] [Server thread/WARN] [Sponge]: /* such that duplications or other game breaking issues could exist.                                                             */
[20:34:11] [Server thread/WARN] [Sponge]: /*                                                                                                                               */
[20:34:11] [Server thread/WARN] [Sponge]: /* Due to the nature of the exception, this is not likely an exception                                                           */
[20:34:11] [Server thread/WARN] [Sponge]: /* that is covered by SpongeForge or Forge itself, and therefore should                                                          */
[20:34:11] [Server thread/WARN] [Sponge]: /* be reported to the mod/plugin author first prior to reporting to                                                              */
[20:34:11] [Server thread/WARN] [Sponge]: /* Sponge or Forge.                                                                                                              */
[20:34:11] [Server thread/WARN] [Sponge]: /*                                                                                                                               */
[20:34:11] [Server thread/WARN] [Sponge]: /* Owning Mod/Plugin: redprotect                                                                                                 */
[20:34:11] [Server thread/WARN] [Sponge]: /* Exception:                                                                                                                    */
[20:34:11] [Server thread/WARN] [Sponge]: /*     java.lang.NullPointerException: null                                                                                      */
[20:34:11] [Server thread/WARN] [Sponge]: /*     br.net.fabiozumbi12.RedProtect.Sponge.RedProtect.onReloadPlugins(RedProtect.java:289)                                     */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.event.listener.GameReloadEventListener_RedProtect_onReloadPlugins10.handle(Unknown Source)       */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97)                                      */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)                                    */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458)                            */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419)                                    */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:467)                                       */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:249)                                                        */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.command.SpongeCommandFactory.lambda$createSpongePluginsCommand$10(SpongeCommandFactory.java:629) */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255)              */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)                                              */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355)                        */
[20:34:11] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360)                              */
[20:34:11] [Server thread/WARN] [Sponge]: /*     net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665)                                                   */
[20:34:11] [Server thread/WARN] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:433)                                    */
[20:34:11] [Server thread/WARN] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:398)                                     */
[20:34:11] [Server thread/WARN] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                               */
[20:34:11] [Server thread/WARN] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                        */
[20:34:11] [Server thread/WARN] [Sponge]: /*     java.lang.Thread.run(Thread.java:748)                                                                                     */
[20:34:11] [Server thread/WARN] [Sponge]: /*********************************************************************************************************************************/

**Comment by APlayGames** [comment]
Also after removing RedProtect configs the only things that were created in the redprotect folder are an empty data folder, schematics folder with house1.schem and economy.conf there is no even config.cfg

**Comment by FabioZumbi12** [comment]
Probably the error is related with the latest versions of Sponge, as Redprotect for sponge is not updated for a long time. I think i need to update to latest sponge version, but i have no estimated time to do this.

**Comment by FabioZumbi12** [comment]
Btw, in your logs: `RedProtect-7.6.7-b342-Universal.jar`

You still not using the latest dev build. Please download the 7.7.3: http://host.areaz12server.net.br:8081/job/RedProtect

**Comment by APlayGames** [comment]
I just forgot to upload logs with 7.7.3, but the same issue is happening on that version too

**Comment by FabioZumbi12** [comment]
OK, but i need the logs unsing the latest version because the code lines is different from old version. I need to find the exact line with problem.

**Comment by APlayGames** [comment]
ok tomorrow I will upload it, it's evening now

**Comment by APlayGames** [comment]
[debug.log](https://github.com/FabioZumbi12/RedProtect/files/6099537/debug.log)

**Comment by APlayGames** [comment]
[debug.log](https://github.com/FabioZumbi12/RedProtect/files/6100571/debug.log)

**Comment by FabioZumbi12** [comment]
In your logs: `Adding RedProtect-7.6.3-b270-Universal.jar to the plugin list`
You still using the outdated version

**Comment by APlayGames** [comment]
wait what that's impossible

**Comment by APlayGames** [comment]
this is my plugins file 
![image](https://user-images.githubusercontent.com/44097279/113129512-47203f00-921b-11eb-83d6-3884e284e137.png)

**Comment by APlayGames** [comment]
I also have a issue that I removed mod called Midnight from server files and after many server restarts the mod still exists. Maybe this is a similar problem
