### ISSUE TITLE
[Problema] RedProtect não iniciando na versão 1.7.10

### ISSUE THREAD

**Issue by Zaureon** [FabioZumbi12/RedProtect#760]
Eu estou usando o RedProtect para meu servidor da 1.7.10 porém ele dá o seguinte erro: 

```
> [20:12:06 ERROR]: Error occurred while enabling RedProtect v7.7.2 (Is it up to date?)
java.lang.NoClassDefFoundError: guava10/com/google/common/reflect/TypeToken
at ninja.leaping.configurate.ConfigurationOptions.defaults(ConfigurationOptions.java:68) ~[?:?]
at ninja.leaping.configurate.loader.AbstractConfigurationLoader$Builder.<init>(AbstractConfigurationLoader.java:210) ~[?:?]
at ninja.leaping.configurate.hocon.HoconConfigurationLoader$Builder.<init>(HoconConfigurationLoader.java:109) ~[?:?]
at ninja.leaping.configurate.hocon.HoconConfigurationLoader.builder(HoconConfigurationLoader.java:99) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.config.ConfigManager.<init>(ConfigManager.java:68) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:195) ~[?:?]
at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.onEnable(RedProtect.java:137) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-26]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-26]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-26]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:439) [CraftServer.class:1.7.10-26]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:373) [CraftServer.class:1.7.10-26]
at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:522) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:496) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:456) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:338) [lt.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

Versão do Plugin: v7.7.2
Plataforma: Mohist 1.7.10

**Comment by FabioZumbi12** [comment]
ALready fixed on latest dev builds available on http://host.areaz12server.net.br:8081/job/RedProtect/
