### ISSUE TITLE
[Suggestion]  Add Fakeplayer list for Redprotect to ignore

### ISSUE THREAD

**Issue by Irgendwer01** [FabioZumbi12/RedProtect#778]
**Is your feature request related to a problem? Please describe.**
Yes, my issue is im using Mohist and Fakeplayers not work as they should in Claims and outside claims (can't break or place) and the console just spams that it can't passthrough Blockbreakevent, the tested mod is Actually Additions but other Players reported that other are not working too.

**Describe the solution you'd like**
Adding a Fakeplayer list to the Config of Redprotect that Redprotect won't will checkup the permissions for that Fakeplayer.

**Describe alternatives you've considered**
tbh none.

**Additional context**
Here's the full thing it spams:
[13:30:11 ERROR]: Could not pass event BlockBreakEvent to RedProtect v7.7.2
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1273) [CraftEventFactory.class:?]
        at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:129) [BlockEvent$BreakEvent.class:?]
        at de.ellpeck.actuallyadditions.mod.util.WorldUtil.fireFakeHarvestEventsForDropChance(WorldUtil.java:293) [WorldUtil.class:?]
        at de.ellpeck.actuallyadditions.mod.tile.TileEntityMiner.mine(TileEntityMiner.java:134) [TileEntityMiner.class:?]
        at de.ellpeck.actuallyadditions.mod.tile.TileEntityMiner.updateEntity(TileEntityMiner.java:98) [TileEntityMiner.class:?]
        at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.update(TileEntityBase.java:220) [TileEntityBase.class:?]
        at net.minecraft.world.World.redirect$zzj000$tileEntityUpdate(World.java:4668) [amu.class:?]
        at net.minecraft.world.World.updateEntities(World.java:2231) [amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:744) [oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:903) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.

LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for '41c82c87-7afb-4024-ba57-13d2c99cae77' (an offline player) from the database

Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:154) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userHasPermission(LuckPermsVaultPermission.java:173) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerHas(AbstractVaultPermission.java:149) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.PermissionHandler.hasVaultPerm(PermissionHandler.java:123) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.PermissionHandler.hasPerm(PermissionHandler.java:59) ~[?:?]
        at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.BlockListener.onBlockBreak(BlockListener.java:315) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor198.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
        ... 17 more

**Comment by FabioZumbi12** [comment]
This is not a bug. as suggested on message:
`b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
to true in the LuckPerms configuration file. However, please use this only as
a last resort.`

Its a warning about offline player (fake player)
