### ISSUE TITLE
might be an idea to take a look for 1.17[BUG]  - buy rent region

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#779]
```
[09:10:52] [Server thread/INFO]: [BuyRentRegion] Disabling BuyRentRegion v7.7.3
[09:10:52] [Server thread/ERROR]: [BuyRentRegion] An error occurred during shutdown.
java.lang.NullPointerException: Cannot invoke "br.net.fabiozumbi12.buyrentregion.config.DigiFile.save()" because "this.regionCounts" is null
	at br.net.fabiozumbi12.buyrentregion.BuyRentRegion.onDisable(BuyRentRegion.java:144) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at br.net.fabiozumbi12.buyrentregion.BuyRentRegion.onEnable(BuyRentRegion.java:109) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by EpiCanard** [comment]
The bug happen when vault or the economy plugin is missing (or not enabled) with BuyRentRegion addon. So it's not a bug specific for 1.17 but for every version

**Comment by CloudeLecaw** [comment]
fixed now where economy and other work
