### ISSUE TITLE
[BUG] /rp list is no longer displayed

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#832]
I just installed the latest RedProtect version on our server.
If you want to call up the list of a player with the command **/rp list NAME**, all you have to do is:
_Region created by: name_

but no more listing of the zones he created.
And the following error message is written in the console.

RP-Version: **RedProtect_8.1.0-Build421.jar**

>....
[09:46:25 INFO]: Blueeyestar issued server command: /rp list Blueeyestar

[09:46:25 WARN]: [RedProtect] Plugin RedProtect v8.1.0-SNAPSHOT generated an exception while executing task 1392077
java.lang.NoClassDefFoundError: br/net/fabiozumbi12/UltimateFancy/UltimateFancy
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandlers.lambda$getRegionforList$2(CommandHandlers.java:640) ~[RedProtect_8.1.0-Build421.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-503]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-503]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: br.net.fabiozumbi12.UltimateFancy.UltimateFancy
	... 7 more
>....

**Comment by aurel85** [comment]
I confirm, it's corrected. Thanks !

**Comment by CloudeLecaw** [comment]
i can confirm its solved in Build422
