### ISSUE TITLE
[BUG] Could not pass event LingeringPotionSplashEvent to RedProtect

### ISSUE THREAD

**Issue by servicomcr** [FabioZumbi12/RedProtect#865]
[16:45:01 ERROR]: Could not pass event LingeringPotionSplashEvent to RedProtect v8.1.2-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "org.bukkit.potion.PotionData.getType()" because the return value of "org.bukkit.inventory.meta.PotionMeta.getBasePotionData()" is null
        at RedProtect.jar/br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.denyPotion(RedProtectUtil.java:123) ~[RedProtect.jar:?]
        at RedProtect.jar/br.net.fabiozumbi12.RedProtect.Bukkit.helpers.VersionHelperLatest.denyEntLingPot(VersionHelperLatest.java:63) ~[RedProtect.jar:?]
        at RedProtect.jar/br.net.fabiozumbi12.RedProtect.Bukkit.listeners.Compat19.onLingerPotion(Compat19.java:217) ~[RedProtect.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor801.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.enchantment.impl.bow.DragonfireArrowsEnchant.createCloud(DragonfireArrowsEnchant.java:142) ~[ExcellentEnchants-4.2.1.jar:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.enchantment.impl.bow.DragonfireArrowsEnchant.onHit(DragonfireArrowsEnchant.java:103) ~[ExcellentEnchants-4.2.1.jar:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.registry.wrapper.DataGathers$4.useEnchant(DataGathers.java:152) ~[ExcellentEnchants-4.2.1.jar:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.registry.wrapper.DataGathers$4.useEnchant(DataGathers.java:117) ~[ExcellentEnchants-4.2.1.jar:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.registry.wrapper.WrappedEvent.lambda$execute$0(WrappedEvent.java:48) ~[ExcellentEnchants-4.2.1.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.registry.wrapper.WrappedEvent.lambda$execute$1(WrappedEvent.java:44) ~[ExcellentEnchants-4.2.1.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.registry.wrapper.WrappedEvent.execute(WrappedEvent.java:43) ~[ExcellentEnchants-4.2.1.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1517) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:209) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:49) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.ThrownEnderpearl.tick(ThrownEnderpearl.java:134) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1359) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1466) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:801) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:781) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1842) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:45:01 ERROR]: Could not pass event LingeringPotionSplashEvent to RedProtect v8.1.2-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "org.bukkit.potion.PotionData.getType()" because the return value of "org.bukkit.inventory.meta.PotionMeta.getBasePotionData()" is null
        at RedProtect.jar/br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.denyPotion(RedProtectUtil.java:123) ~[RedProtect.jar:?]
        at RedProtect.jar/br.net.fabiozumbi12.RedProtect.Bukkit.helpers.VersionHelperLatest.denyEntLingPot(VersionHelperLatest.java:63) ~[RedProtect.jar:?]
        at RedProtect.jar/br.net.fabiozumbi12.RedProtect.Bukkit.listeners.Compat19.onLingerPotion(Compat19.java:217) ~[RedProtect.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor801.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.enchantment.impl.bow.DragonfireArrowsEnchant.createCloud(DragonfireArrowsEnchant.java:142) ~[ExcellentEnchants-4.2.1.jar:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.enchantment.impl.bow.DragonfireArrowsEnchant.onDamage(DragonfireArrowsEnchant.java:109) ~[ExcellentEnchants-4.2.1.jar:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.registry.wrapper.DataGathers$5.useEnchant(DataGathers.java:199) ~[ExcellentEnchants-4.2.1.jar:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.registry.wrapper.DataGathers$5.useEnchant(DataGathers.java:156) ~[ExcellentEnchants-4.2.1.jar:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.registry.wrapper.WrappedEvent.lambda$execute$0(WrappedEvent.java:48) ~[ExcellentEnchants-4.2.1.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.registry.wrapper.WrappedEvent.lambda$execute$1(WrappedEvent.java:44) ~[ExcellentEnchants-4.2.1.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at ExcellentEnchants-4.2.1.jar/su.nightexpress.excellentenchants.registry.wrapper.WrappedEvent.execute(WrappedEvent.java:43) ~[ExcellentEnchants-4.2.1.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:271) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1213) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1203) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1132) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1095) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1251) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2394) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1541) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1041) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1235) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.ThrownEnderpearl.onHit(ThrownEnderpearl.java:93) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:233) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:212) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:49) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.ThrownEnderpearl.tick(ThrownEnderpearl.java:134) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1359) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1466) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:801) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:781) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1842) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by FabioZumbi12** [comment]
Fixed on dev builds http://host.areaz12server.net.br:8081/job/RedProtect/
