### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by 5igm** [FabioZumbi12/RedProtect#89]
spongeforge-1.10.2-2052-5.0.0-BETA-1679
RedProtect_Sponge
[22:12:59] [Server thread/ERROR] [Sponge/]: Could not pass DamageEntityEvent$Impl to Plugin{id=br.net.fabiozumbi12.redprotect, name=RedProtect, version=6.5.0, description=Complete antigrief plugin, authors=[FabioZumbi12], source=E:\sponge-1.10.2\mods\RedProtect_Sponge.jar}
java.lang.UnsupportedOperationException: A method was invoked on a dummy class, due to the static field HUNGER not being initialized (most likely in a CatalogType-related class).
Method: public abstract java.lang.String org.spongepowered.api.CatalogType.getName()
	at org.spongepowered.api.util.dummy.DamageType$DummyClass.getName(Unknown Source) ~[?:?]
	at br.net.fabiozumbi12.redprotect.listeners.RPPlayerListener.onEntityDamageEvent(RPPlayerListener.java:520) ~[RPPlayerListener.class:?]
	at org.spongepowered.common.event.listener.DamageEntityEventListener_RPPlayerListener_onEntityDamageEvent154.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:390) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:362) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
	at net.minecraft.entity.EntityLivingBase.damageEntityHook(EntityLivingBase.java:572) [sf.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:420) [sf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1022) [zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:543) [lu.class:?]
	at toughasnails.thirst.ThirstHandler.update(ThirstHandler.java:83) [ThirstHandler.class:?]
	at toughasnails.handler.ExtendedStatHandler.onPlayerTick(ExtendedStatHandler.java:69) [ExtendedStatHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_95_ExtendedStatHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:131) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:100) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:365) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:382) [zs.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:292) [zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) [lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$0(NetHandlerPlayServer.java:230) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) [me.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by FabioZumbi12** [comment]
Posted on Redprotect-Sponge github: https://github.com/FabioZumbi12/Sponge-Redprotect-19/issues/3
