### ISSUE TITLE
mysql error.. new table

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#9]
[08:27:24] [Server thread/INFO]: [RedProtect] Enabling RedProtect v6.3.4
[08:27:25] [Server thread/INFO]: Redprotect: [All configurations loaded!][m
[08:27:25] [Server thread/INFO]: Redprotect: [[0;33;22mYour lang file is outdated. Probally need strings updates![m][m
[08:27:25] [Server thread/INFO]: Redprotect: [[0;33;22mLang file version: 6.3.3[m][m
[08:27:25] [Server thread/INFO]: Redprotect: [Language file loaded - Using: EN-US][m
[08:27:25] [Server thread/INFO]: Redprotect: [Conected to redprotect_s1 via Mysql!][m
[08:27:25] [Server thread/INFO]: Redprotect: [[0;31;1m[21mCold not add the colluns to table region.[m][m
[08:27:25] [Server thread/INFO]: Redprotect: [Vault found. Hooked.][m
[08:27:25] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'redprotect_s1.region' doesn't exist
[08:27:25] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:27:25] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[08:27:25] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[08:27:25] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[08:27:25] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[08:27:25] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[08:27:25] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[08:27:25] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[08:27:25] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[08:27:25] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[08:27:25] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[08:27:25] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[08:27:25] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
[08:27:25] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474)
[08:27:25] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.WorldMySQLRegionManager.getTotalRegionNum(WorldMySQLRegionManager.java:588)
[08:27:25] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RegionManager.getTotalRegionsNum(RegionManager.java:284)
[08:27:25] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:168)
[08:27:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[08:27:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[08:27:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:27:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[08:27:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[08:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[08:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[08:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[08:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[08:27:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:561)
[08:27:25] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[08:27:25] [Server thread/INFO]: Redprotect: [Theres 0 regions on (mysql) database!][m
[08:27:25] [Server thread/INFO]: Redprotect: [[0;32;1m[21mRedProtect v6.3.4 enabled.[m][m

**Comment by FabioZumbi12** [comment]
I got this same error! You need to remove all world databases before install the plugin again! Try this version and see if solves the problem: http://areaz12server.net.br/download/RedProtect.jar

**Comment by mat41997** [comment]
thanks.

logs,
[09:35:09] [Server thread/INFO]: [RedProtect] Enabling RedProtect v6.3.4
[09:35:09] [Server thread/INFO]: Redprotect: [All configurations loaded!][m
[09:35:09] [Server thread/INFO]: Redprotect: [Language file loaded - Using: EN-US][m
[09:35:09] [Server thread/INFO]: Redprotect: [Created database 'redprotect_s1'!][m
[09:35:10] [Server thread/INFO]: Redprotect: [Created table: 'Region'!][m
[09:35:10] [Server thread/INFO]: Redprotect: [Created table: 'Region Flags'!][m
[09:35:10] [Server thread/INFO]: Redprotect: [Conected to redprotect_s1 via Mysql!][m
[09:35:10] [Server thread/INFO]: Redprotect: [Vault found. Hooked.][m
[09:35:10] [Server thread/INFO]: Redprotect: [Theres 0 regions on (mysql) database!][m
[09:35:10] [Server thread/INFO]: Redprotect: [[0;32;1m[21mRedProtect v6.3.4 enabled.[m][m
